import { Show } from "../types/Show";

export const crimeSeries: Show[] = [
{
    id: "johan-falk",
    title:" Johan Falk ",
    country: "Sweden",
    language: "Swedish",
    prodLocation: ["Sweden"],
    posterUrl: "https://image.tmdb.org/t/p/original/qRhEJUcOVtgMEno5LEkZZ190vDy.jpg",
    firstAirDate: "October 29, 1999",
    lastAirDate: "Present",
    tags: ["Crime", "Action", "Thriller"],
},
{
    id: "wallander",
    title:"Wallander ",
    country: "Sweden",
    language: "Swedish",
    prodLocation: ["Sweden"],
    posterUrl: "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p527401_b_v8_ao.jpg",
    firstAirDate: "January 14, 2005",
    lastAirDate: "October 23, 2013",
    tags: ["Crime", "Drama", "Mystery"],
},
{
    id: "beck",
    title:"Beck",
    country: "Sweden",
    language: "Swedish",
    prodLocation: ["Sweden"],
    posterUrl: "https://resizing.flixster.com/U23XP3plq2jdUYjihAh_y8I2_Js=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p8998638_b_v8_ae.jpg",
    firstAirDate: "June 27, 1997",
    lastAirDate: "TBA",
    tags: ["Crime", "Drama", "Mystery"],
},
{
    id: "the-sandhamn-murders",
    title:"Morden i Sandhamn ",
    country: "Sweden",
    language: "Swedish",
    prodLocation: ["Sweden"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BY2FhMzY2NGMtMDk1Yy00ODE2LWJjODItNTAzNmY3NzU4ZTA2XkEyXkFqcGc@._V1_.jpg",
    firstAirDate: "December 20, 2010",
    lastAirDate: "TBA",
    tags: ["Crime", "Drama", "Mystery"],
},
{
    id: "rebecka-martinsson-series",
    title:"Rebecka Martinsson",
    country: "Sweden",
    language: "Swedish",
    prodLocation: ["Sweden"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BODM0MDZlYzYtMjZiMC00MDM4LTg4YzctYzIzOTcxM2I4NmNkXkEyXkFqcGc@._V1_.jpg",
    firstAirDate: "March 8, 2017",
    lastAirDate: "TBA",
    tags: ["Crime", "Drama", "Mystery"],
},
{
    id: "backstrom",
    title:"Bäckström",
    country: "Sweden",
    language: "Swedish",
    prodLocation: ["Sweden"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNDEzZjUxYzctNzNmNS00YTFkLWFmZmUtMjk5YWVkOTE2ODMzXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    firstAirDate: "March 23, 2020",
    lastAirDate: "TBA",
    tags: ["Crime", "Drama", "Mystery"],
},
{
    id: "the-bridge",
    title:"Bron",
    country: "Sweden",
    language: "Swedish",
    prodLocation: ["Sweden"],
    posterUrl: "https://nfimageservice.azureedge.net/image/27ef27f6-7679-4d51-9869-fae44f24edf1?width=400",
    firstAirDate: "September 21, 2011",
    lastAirDate: "February 18, 2018",
    tags: ["Crime", "Drama", "Mystery"],
},
{
    id: "maria-wern-series",
    title:"Maria Wern ",
    country: "Sweden",
    language: "Swedish",
    prodLocation: ["Sweden"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BZTcxMjNjMzMtZWRhMC00YjJlLTg1MDEtMjVlMmYxNTZjOGU1XkEyXkFqcGc@._V1_.jpg",
    firstAirDate: "September 16, 2008",
    lastAirDate: "TBA",
    tags: ["Crime", "Drama", "Mystery"],
},
{
    id: "califate",
    title:"Kalifat",
    country: "Sweden",
    language: "Swedish",
    prodLocation: ["Sweden"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BYjU0NWQ4NjYtOGQ3OS00OGU5LWE3YmEtOTBkM2Q5NGQzY2ZjXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    firstAirDate: "January 12, 2020",
    lastAirDate: "February 9, 2020",
    tags: ["Crime", "Drama", "Thriller"],
},
{
    id: "the-glass-dome",
    title:"Glaskupan",
    country: "Sweden",
    language: "Swedish",
    prodLocation: ["Sweden"],
    posterUrl: "https://c3687.eu-central-1.linodeobjects.com/2023/12/glaskupan-poster.webp",
    firstAirDate: "April 5, 2025",
    lastAirDate: "TBA",
    tags: ["Crime", "Drama", "Mystery"],
},
{
    id: "a-nearly-normal-family",
    title:"En helt vanlig familj ",
    country: "Sweden",
    language: "Swedish",
    prodLocation: ["Sweden"],
    posterUrl: "https://www.moviezine.se/wp-content/uploads/2025/02/large_605e1e955a076981a4f2217b02f3b15c-zRvD6BUjHSkV1Mqizvi8M5oyY1e.jpg",
    firstAirDate: "November 24,, 2023",
    lastAirDate: "TBA",
    tags: ["Crime", "Drama", "Thriller"],
},
{
    id: "blind-spot",
    title:"Blindspår",
    country: "Sweden",
    language: "Swedish",
    prodLocation: ["Sweden"],
    posterUrl: "https://image.tmdb.org/t/p/w500/mGdCkmhg2fuaiFmwxdPm4zTFB2r.jpg",
    firstAirDate: "January 24, 2025",
    lastAirDate: "TBA",
    tags: ["Crime", "Drama", "Thriller"],
},
{
    id: "the-are-murders",
    title:"Åremorden",
    country: "Sweden",
    language: "Swedish",
    prodLocation: ["Sweden"],
    firstAirDate: "February 6, 2025",
    tags: ["Crime", "Drama", "Mystery"],
    posterUrl: "https://c3687.eu-central-1.linodeobjects.com/2025/01/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vNjVhMWVjZDctMzBmYi00NjZmLWJkZDYtMDJmNjg3NmJhYWQ0LmpwZw.jpeg"
},
{
    id: "knutby",
    title:"Knutby",
    country: "Sweden",
    language: "Swedish",
    prodLocation: ["Sweden"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMTI2ODZjNmMtYTdhMS00YWE2LThhNjctNzcxYzI5NDc0NzM5XkEyXkFqcGc@._V1_.jpg",
    firstAirDate: "November 11, 2021",   
    tags: ["Crime", "Drama", "Mystery"],
},
{
    id: "riding-in-darkness",
    title:"Nattryttarna",
    country: "Sweden",
    language: "Swedish",
    prodLocation: ["Sweden"],
    posterUrl: "https://www.moviezine.se/wp-content/uploads/2025/02/large_f396b5cf3fc0ec57b0b3727d9a5f1063-download_20_1.jpg",
    firstAirDate: "October 31, 2022",   
    lastAirDate: "TBA",
    tags: ["Crime", "Drama", "Mystery"],
},
{
    id: "quicksand",
    title:"Störst av allt",
    country: "Sweden",
    language: "Swedish",
    prodLocation: ["Sweden"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMmU1MTk1MWMtMDYzZC00OTU5LWI5YmUtMTk0NWRjMDdiYmExXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    firstAirDate: "April 5, 2019",  
    lastAirDate: "April 5, 2019",
    tags: ["Crime", "Drama", "Thriller"],
},
{
    id: "irene-huss-series",
    title:"Irene Huss",
    country: "Sweden",
    language: "Swedish",
    prodLocation: ["Sweden"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BOTUwMzdhOGItZTY1Ni00Y2Y4LWJlNjQtMWY0MTI4MzAxY2Y0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",

},
{
    id: "Annika Bengtzon",
    title:"Annika Bengtzon",
    country: "Sweden",
    language: "Swedish",
    prodLocation: ["Sweden"],
},
{
    id: "Heder",
    title:"Heder",
    country: "Sweden",
    language: "Swedish",
    prodLocation: ["Sweden"],
},
{
    id: "Gåsmamman ",
    title:"Gåsmamman ",
    country: "Sweden",
    language: "Swedish",
    prodLocation: ["Sweden"],
},
{
    id: "100-code",
    title:"100 Code",
    country: "Sweden",
    language: "Swedish",
    prodLocation: ["Sweden"],
},
{
    id: "21-jump-street",
    title:"21 Jump Street",
    country: "USA",
    language: "English",
}, 

{
    id: "911",
    title:"911",
    country: "USA",
    language: "English",
}, 

{
    id: "criminal-minds",
    title:"Criminal Minds",
    country: "USA",
    language: "English",
}, 

{
    id: "bones",
    title:"Bones",
    country: "USA",
    language: "English",
}, 

{
    id: "castle",
    title:"Castle",
    country: "USA",
    language: "English",
},

{
    id: "chicago-pd",
    title:"Chicago PD",
    country: "USA",
    language: "English",
},  

{
    id: "csi",
    title:"CSI",
    country: "USA",
    language: "English",
},

{
    id: "dexter",
    title:"Dexter",
    country: "USA",
    language: "English",
},  

{
    id: "fbi",
    title:"FBI",
    country: "USA",
    language: "English",
}, 

{
    id: "hawaii-five-0",
    title:"Hawaii Five-0",
    country: "USA",
    language: "English",
}, 

{
    id: "law-and-order",
    title:"Law and Order",
    country: "USA",
    language: "English",
}, 

{
    id: "luther",
    title:"Luther",
    country: "USA",
    language: "English",
}, 

{
    id: "dicte",
    title:"Dicte",
    country: "Denmark",
    language: "danish",
}, 

{
    id: "harry-hole",
    title:"Harry Hole",
    country: "Norway",
    language: "Norwegian",
},

{
    id: "magnum-pi",
    title:"Magnum PI",
    country: "USA",
    language: "English",
},  

{
    id: "modus",
    title:"Modus",
    country: "Sweden",
    language: "Swedish",
}, 

{
    id: "ncis",
    title:"NCIS",
    country: "USA",
    language: "English",
}, 

{
    id: "the-rookie",
    title:"The Rookie",
    country: "USA",
    language: "English",
}, 

{
    id: "swat",
    title:"SWAT",
    country: "USA",
    language: "English",
}, 

{
    id: "the-midsomer-murders",
    title:"The Midsomer Murders",
    country: "UK",
    language: "English",
}, 

{
    id: "white-collar",
    title:"White Collar",
    country: "USA",
    language: "English",
}, 

{
    id: "the-x-files",
    title:"The X-Files",
    country: "USA",
    language: "English",
}, 
]