import { Show } from "../types/Show";


export const fantasySeries: Show[] = [
  {
    id:"game-of-thrones", 
    title: "Game of Thrones", 
    posterUrl: "https://i.redd.it/game-of-thrones-or-the-walking-dead-v0-nd3axk0385ah1.jpg?width=1000&format=pjpg&auto=webp&s=5d74b10b63cfb2493eb5e5f650a513a50b110b1a",
    plot: "In the mythical continent of Westeros, several powerful families fight for control of the Seven Kingdoms. As conflict erupts in the kingdoms of men, an ancient enemy rises once again to threaten them all. Meanwhile, the last heirs of a recently usurped dynasty plot to take back their homeland from across the Narrow Sea.",
    basedOn: true,
    creator: [
      "David Benioff",
      "D. B. Weiss",
    ],
    mainCharacters:  [
      {
        id:	"eddard-stark",
        firstName: "Eddard",
        lastName: "Stark",			
        imageUrl: "https://i.pinimg.com/736x/8f/a8/d7/8fa8d7cb17eaea1f9518e34ac2983f1d.jpg",
        actor: "Sean Bean",
        nickname: ["Ned"],
        promo: true,
      },
      {
        id: "jaime-lannister",
        firstName: "Jaime",
        lastName: "Lannister",
        imageUrl: "https://i.pinimg.com/1200x/09/97/05/099705b94de38019981f1a3846889337.jpg",
        actor: "Nikolaj Coster-Waldau",
        promo: true,
      },
      {
        id: "robert-baratheon",
        firstName: "Robert",
        lastName: "Baratheon",	
        imageUrl: "https://i.pinimg.com/736x/b2/0e/e5/b20ee5400068f1f92d1627309c8efe3b.jpg",
        actor: "Mark Addy",
        promo: true,
      },
      {
        id:	"catelyn-stark",
        firstName: "Catelyn",
        lastName: "Stark",	
        imageUrl: "https://i.pinimg.com/736x/6e/9a/47/6e9a474dcd2efe0249e0a4c973bfea34.jpg",
        actor: "Michelle Fairley",
        promo: true
      },
      {
        id: "cersei-lannister",
        firstName: "Cersei",
        lastName:"Lannister",
        imageUrl: "https://i.pinimg.com/736x/94/6a/c9/946ac944c3c510088dfd6a63c77e8a73.jpg",
        actor: "Lena Headey",
        promo: true,	
      },
      {
        id: "daenerys-targaryen",
        firstName: "Daenerys",
        lastName: "Targaryen",
        imageUrl: "https://i.pinimg.com/736x/b1/b9/8b/b1b98bc7ea07224073b1cf98da3ac0de.jpg",
        actor: "Emilia Clarke",
        promo: true,
      },
      {
        id: "jorah-mormont",
        firstName: "Jorah",
        lastName: "Mormont",
        imageUrl: "https://i.pinimg.com/736x/6b/20/d1/6b20d1601d586340c6a20a5c831eff4c.jpg",
        actor: "Iain Glen",
        promo: true,
      },
      {
        id:"viserys-targaryen",
        firstName: "Viserys",
        lastName: "Targaryen",
        imageUrl: "https://i.pinimg.com/1200x/86/40/d3/8640d38934caa73367978dd2e3d2120e.jpg",
        actor: "Harry Lloyd",
        promo: true,
      },
      {
        id: "jon-snow",
        firstName: "Jon",
        lastName: "Snow",
        imageUrl: "https://i.pinimg.com/1200x/1b/ee/de/1beede75606ba190d6b12593121ccadc.jpg",
        actor: "Kit Harington",
        promo: true,
      },
      {
        id: "robb-stark",
        firstName: "Robb",
        lastName: "Stark",
        imageUrl: "https://i.pinimg.com/736x/a4/8a/d9/a48ad96bb5be9e5bf0d8347e0e3f3487.jpg",
        actor: "Richard Madden",
        promo: true,
      },
      {
        id: "sansa-stark",
        firstName: "Sansa",
        lastName: "Stark",
        imageUrl: "https://i.pinimg.com/736x/5d/8e/20/5d8e20159512e3f41702a3a93bd4bcef.jpg",
        actor: "Sophie Turner",
        promo: true
      },
      {
        id: "arya-stark",
        firstName: "Arya",
        lastName: "Stark",
        imageUrl: "https://i.pinimg.com/736x/65/8e/f9/658ef910c0933e514156e8fab0a68bfc.jpg",
        actor: "Maisie Williams", 
        promo: true,
      },
      {
        id: "theon-greyjoy",
        firstName: "Theon",
        lastName: "Greyjoy",
        imageUrl: "https://i.pinimg.com/736x/04/66/90/04669034ee9cb29bd1170412047cbd2b.jpg",
        actor: "Alfie Allen",
        promo: true,
      },
      {
        id:	"bran-stark",	
        firstName: "Bran",
        lastName: "Stark",
        imageUrl: "https://i.pinimg.com/736x/cd/ea/2e/cdea2e483deefcfe203120cb3dbb4246.jpg",
        actor: "Isaac Hempstead Wright",
        promo: true,
      },
      {
        id: "joffrey-baratheon",	
        firstName: "Joffrey",
        lastName: "Baratheon",
        imageUrl: "https://i.pinimg.com/736x/88/b6/b3/88b6b3d16688dcd667a7ef734fc61be2.jpg",
        actor: "Jack Gleeson",
        promo: true,
      },
      {
        id: "sandor-clegane",
        firstName: "Sandor",
        lastName: "Clegane",
        imageUrl: "https://i.pinimg.com/736x/fd/90/a6/fd90a6dd810a6824ec81040cdb6cb78e.jpg",
        actor: "Rory McCann",
        nickname: [
          "The Hound"
        ],
        goesByNickname: true,
        promo: true,
      },
      {
        id: "tyrion-lannister",
        firstName: "Tyrion",
        lastName: "Lannister",
        imageUrl: "https://i.pinimg.com/736x/62/bc/63/62bc638baa42394d340c5e476871ab1e.jpg",
        actor: "Peter Dinklage",
        promo: true,
      },
      {
        id: "khal-drogo",		
        firstName: "Khal",
        lastName: "Drogo",
        imageUrl: "https://i.pinimg.com/1200x/6d/18/79/6d187964157d0cad473bbcc773245421.jpg",
        actor: "Jason Momoa",
        promo: true,
      },
      {
        id: "littlefinger-baelish",	
        firstName: "Petyr",
        lastName: "Baelish",
        imageUrl: "https://i.pinimg.com/736x/83/1f/c5/831fc5d8d86f61f152127d413a0af31f.jpg",
        actor: "Aidan Gillen",
        nickname: ["Littlefinger"],
        goesByNickname: true,
        promo: true,
      },
      {
        id: "davos-seaworth",	
        firstName: "Davos",
        lastName: "Seaworth",
        imageUrl: "https://i.pinimg.com/736x/be/bc/98/bebc9834d9769bbaa9fc8d4916aafe13.jpg",
        actor: "Liam Cunningham",
        promo: true,
      },
      {
        id: "samwell-tarly",
        firstName: "Samwell",
        lastName: "Tarly",
        imageUrl: "https://i.pinimg.com/1200x/bb/e6/fa/bbe6fa0591e815ceb99ea57867d2d1c7.jpg",
        actor: "John Bradley",
        promo: true,
      },
      {
        id: "stannis-baratheon",
        firstName: "Stannis",
        lastName: "Baratheon",
        imageUrl: "https://i.pinimg.com/736x/68/9b/12/689b12dd009667044711549b3281611b.jpg", 
        actor: "Stephen Dillane",
      },
      {
        id: "melisandre",	
        label: "Melisandre",
        imageUrl: "https://i.pinimg.com/1200x/f1/fa/2f/f1fa2f3aca86f14704bd6918a6c7b661.jpg",
        actor: "Carice van Houten",
        promo: true,
      },
      {
        id: "jeor-mormont",
        firstName: "Jeor",
        lastName: "Mormont",
        imageUrl: "https://i.pinimg.com/736x/2e/53/f3/2e53f3aa3487a1d0d0604b2d4094492e.jpg",
        actor: "James Cosmo",
        promo: true,
      },
      {
        id: "bronn",
        firstName: "Bronn",
        imageUrl: "https://i.pinimg.com/1200x/3a/28/1e/3a281e8fecc8954ec45f6fd9b6af6df6.jpg",
        actor: "Jerome Flynn",
        promo: true,
      },
      {
        id: "varys",
        firstName: "Varys",
        imageUrl: "https://i.pinimg.com/736x/31/37/fc/3137fc49b6d1f653dc303ea9ca64e86a.jpg",
        actor: "Conleth Hill",
        promo: true,
      },
      {
        id:	"shae",	
        firstName: "Shae",
        imageUrl: "https://i.pinimg.com/736x/e7/f2/f3/e7f2f30d4cf10d9da8846312636e9408.jpg",
        actor: "Sibel Kekilli",
        promo: true,
      },
      {
        id:	"margaery-tyrell",		
        firstName: "Margaery",
        lastName: "Tyrell",
        imageUrl: "https://i.pinimg.com/1200x/f5/26/7f/f5267f0667afdf8e6e2b687e0044f4f9.jpg",
        actor: "Natalie Dormer",
        promo: true,
      },
      {
        id: "tywin-lannister",
        firstName: "Tywin",
        lastName: "Lannister",
        imageUrl: "https://i.pinimg.com/736x/f0/57/b4/f057b491fe9204cb9cff0baa3a9f5c40.jpg",
        actor: "Charles Dance",
        promo: true
      },
      {
        id:	"talisa-maegyr",	
        firstName: "Talisa",
        lastName: "Maegyr",
        imageUrl: "https://i.pinimg.com/736x/26/fb/b1/26fbb1a8655d79f5d599b8e473426fb1.jpg",	
        actor: "Oona Chaplin",
        promo: true,
      },
      {
        id:	"ygritte",
        firstName: "Ygritte",
        imageUrl: "https://i.pinimg.com/1200x/75/db/fd/75dbfd812eb8abc1cd76216879b83ad4.jpg",
        actor: "Rose Leslie",
        promo: true,
      },
      {
        id: "gendry-baratheon",
        firstName: "Gendry",	
        lastEpisode: "Baratheon",
        imageUrl: "https://i.pinimg.com/736x/50/a3/65/50a365cd46d09771f193922ef8bf1939.jpg",
        actor: "Joe Dempsie",
        promo: true,
      },
      {
        id: "tormund-giantsbane",	
        firstName: "Tormund",
        lastName: "Giantsbane",
        imageUrl: "https://i.pinimg.com/736x/b9/47/01/b94701c71707e3b3530e5e31fac66093.jpg",
        actor: "Kristofer Hivju",
        promo: true
      },
      {
        id: "brienne-of-tarth",		
        firstName: "Brienne",
        lastName: "of Tarth",
        imageUrl: "https://i.pinimg.com/736x/d5/6a/97/d56a976cc11fc48076b2815f3fc9aaf6.jpg",
        actor: "Gwendoline Christie",
        promo: true,
      },
      {
        id: "ramsay-bolton",
        firstName: "Ramsay",
        lastName: "Bolton",
        imageUrl: "https://i.pinimg.com/736x/99/e8/31/99e83123cfe214b2d8b6c36868947e79.jpg", 
        actor: "Iwan Rheon",
        promo: true,
      },
      {
        id:	"gilly",
        firstName: "Gilly",
        imageUrl: "https://i.pinimg.com/1200x/b6/c3/5a/b6c35a472fd0aed872d5581b627f4732.jpg",		
        actor: "Hannah Murray",
        promo: true
      },
      {
        id: "daario-naharis",
        firstName: "Daario", 
        lastName: "Naharis",
        imageUrl: "https://i.pinimg.com/736x/36/89/93/36899307f71a333ff6109388769348ef.jpg",
        actor: "Michiel Huisman",
        promo: true,
      },
      {
        id: "missandei",
        firstName: "Missandei",
        imageUrl: "https://i.pinimg.com/736x/47/27/4e/47274e7122bf33b6febba15d0d12c709.jpg",
        actor: "Nathalie Emmanuel",
        promo: true,
      },
      {
        id: "tommen-baratheon",
        firstName: "Tommen",
        lastName: "Baratheon",
        imageUrl: "https://i.pinimg.com/736x/79/b6/5e/79b65e6a28b7159641caefe99d68e20d.jpg",
        actor: "Dean-Charles Chapman",
        promo: true,
      },
      {
        id: "ellaria-sand",
        firstName: "Ellaria",
        lastName: "Sand",
        imageUrl: "https://i.pinimg.com/736x/1f/1b/ae/1f1bae92b0edca2386ffbe5c6b09a7e8.jpg",
        actor: "Indira Varma",
        promo: true,
      },
      {
        id: "jaqen-h'ghar",
        firstName: "Jaqen",
        lastName: "H'ghar",		
        imageUrl: "https://i.pinimg.com/736x/a8/9e/4c/a89e4c25787c02f33bdce1a980ecc6d3.jpg",
        actor: "Tom Wlaschiha",
        promo: true
      },
      {
        id:	"roose-bolton",	
        firstName: "Roose",
        lastName: "Bolton",
        imageUrl: "https://i.pinimg.com/736x/5a/50/bb/5a50bb94c62c1df0f86081d64cbab6c6.jpg",
        actor: "Michael McElhatton",
        promo: true
      },
      {
        id: "the-high-sparrow",
        label: "The High Sparrow",
        imageUrl: "https://static.wikia.nocookie.net/antagonists/images/3/3d/High_Sparrow.jpg/revision/latest?cb=20180422023243",
        actor: "Jonathan Pryce",
        promo: true,
      },
      {
        id: "grey-worm",
        firstName: "Grey",
        lastName: "Worm",
        imageUrl: "https://i.pinimg.com/736x/0d/8c/4f/0d8c4f49e7262613683d7d24d836c715.jpg",
        actor: "Jacob Anderson",
        promo: true,
      },
    ],
    cast: [
      {
        actor: "Sean Bean",
        character:	"Eddard 'Ned' Stark",			
      },
      {
        actor: "Nikolaj Coster-Waldau",
        character: "Jaime Lannister"
      },
      {
        actor: "Mark Addy",
        character:"Robert Baratheon"	
      },
      {
        actor: "Michelle Fairley",
        character:	"Catelyn Stark"	
      },
      {
        actor: "Lena Headey",	
        character: "Cersei Lannister",
      },
      {
        actor: "Emilia Clarke",
        character: "Daenerys Targaryen"
      },
      {
        actor: "Iain Glen",
        character: "Jorah Mormont"
      },
      {
        actor: "Harry Lloyd",
        character:"Viserys Targaryen"
      },
      {
        actor: "Kit Harington",
        character: "Jon Snow"
      },
      {
        actor: "Richard Madden",
        character: "Robb Stark"
      },
      {
        actor: "Sophie Turner",
        character: "Sansa Stark",
      },
      {
        actor: "Maisie Williams", 
        character: "Arya Stark",
      },
      {
        actor: "Alfie Allen",
        character: "Theon Greyjoy"
      },
      {
        actor: "Isaac Hempstead Wright",
        character:	"Bran Stark"	
      },
      {
        actor: "Jack Gleeson",
        character: "Joffrey Baratheon"	
      },
      {
        actor: "Rory McCann",
        character: "Sandor 'The Hound' Clegane",	
      },
      {
        actor: "Peter Dinklage",
        character: "Tyrion Lannister"
      },
      {
        actor: "Jason Momoa",
        character: "Khal Drogo"		
      },
      {
        actor: "Aidan Gillen",
        character: "Petyr 'Littlefinger' Baelish"	
      },
      {
        actor: "Liam Cunningham",
        character: "Davos Seaworth"	
      },
      {
        actor: "John Bradley",
        character: "Samwell Tarly"
      },
      {
        actor: "Stephen Dillane",
        character: "Stannis Baratheon",
      },
      {
        actor: "Carice van Houten",
        character: "Melisandre"	
      },
      {
        actor: "James Cosmo",
        character: "Jeor Mormont"
      },
      {
        actor: "Jerome Flynn",
        character: "Bronn"
      },
      {
        actor: "Conleth Hill",
        character: "Varys"
      },
      {
        actor: "Sibel Kekilli",
        character:	"Shae"	
      },
      {
        actor: "Natalie Dormer",
        character:	"Margaery Tyrell"		
      },
      {
        actor: "Charles Dance",
        character: "Tywin Lannister"
      },
      {
        actor: "Oona Chaplin",
        character:	"Talisa Maegyr"		
      },
      {
        actor: "Rose Leslie",
        character:	"Ygritte"		
      },
      {
        actor: "Joe Dempsie",
        character: "Gendry"	
      },
      {
        actor: "Kristofer Hivju",
        character: "Tormund Giantsbane"	
      },
      {
        actor: "Gwendoline Christie",
        character: "Brienne of Tarth",		
      },
      {
        actor: "Iwan Rheon",
        character: "Ramsay Bolton",
      },
      {
        actor: "Hannah Murray",
        character:	"Gilly"		
      },
      {
        actor: "Michiel Huisman",
        character: "Daario Naharis"
      },
      {
        actor: "Nathalie Emmanuel",
        character: "Missandei"
      },
      {
        actor: "Dean-Charles Chapman",
        character: "Tommen Baratheon"
      },
      {
        actor: "Indira Varma",
        character: "Ellaria Sand"
      },
      {
        actor: "Tom Wlaschiha",
        character: "Jaqen H'ghar"		
        },
      {
        actor: "Michael McElhatton",
        character:	"Roose Bolton"	
      },
      {
        actor: "Jonathan Pryce",
        character: "The High Sparrow"
      },
      {
        actor: "Jacob Anderson",
        character: "Grey Worm"
      },
    ],
    seasons: [
      {
        id: "game-of-thrones-season-1",
        seasonNumber: 1,
        episodeCount: 10,
        premiereDate: "April 17, 2011",	
        finaleDate: "June 19, 2011",
        posterUrl: "https://static.wikia.nocookie.net/gameofthrones/images/1/14/Game_of_Thrones-_Season_1.jpg/revision/latest/scale-to-width-down/1200?cb=20110406150536",
      },
      {
        id: "game-of-thrones-season-2",
        seasonNumber: 2,
        episodeCount: 10,
        premiereDate: "April 1, 2012",
        finaleDate:	"June 3, 2012",	
        posterUrl: "https://static.wikia.nocookie.net/gameofthrones/images/6/64/Game_of_Thrones-_Season_2.jpg/revision/latest?cb=20120301142149",
      },
      {
        id: "game-of-thrones-season-3",
        seasonNumber: 3,
        episodeCount: 10,
        premiereDate: "March 31, 2013",
        finaleDate:	"June 9, 2013",
        posterUrl: "https://www.studioremarkable.com/wp-content/uploads/2013/06/Game-of-Thrones-Season-3-Poster.jpg",
      },
      {
        id: "game-of-thrones-season-4",
        seasonNumber: 4,
        episodeCount: 10,
        premiereDate: "April 6, 2014",
        finaleDate:	"June 15, 2014",
        posterUrl: "https://i.ebayimg.com/images/g/hu8AAOSwWbVmDIT4/s-l400.jpg",
      },
      {
        id: "game-of-thrones-season-5",
        seasonNumber: 5,
        episodeCount: 10,
        premiereDate: "April 12, 2015",
        finaleDate:	"June 14, 2015",
        posterUrl: "https://static.wikia.nocookie.net/gameofthrones/images/5/54/Game_of_Thrones-_Season_5.jpg/revision/latest?cb=20150228004741",
      },
      {
        id: "game-of-thrones-season-6",
        seasonNumber: 6,
        episodeCount: 10,
        premiereDate: "April 24, 2016",
        finaleDate:	"June 26, 2016",
        posterUrl: "https://static.wikia.nocookie.net/gameofthrones/images/3/33/Game_of_Thrones-_Season_6.jpg/revision/latest?cb=20160224183949",
      },
      {
        id: "game-of-thrones-season-7",
        seasonNumber: 7,
        episodeCount:7 ,
        premiereDate: "July 16, 2017",
        finaleDate:	"August 27, 2017",
        posterUrl: "https://static.wikia.nocookie.net/gameofthrones/images/5/54/Game_of_Thrones-_Season_7.jpg/revision/latest?cb=20170523174752",
      },
      {
        id: "game-of-thrones-season-8",
        seasonNumber: 8,
        episodeCount: 6,
        premiereDate: "April 14, 2019",
        finaleDate:	"May 19, 2019",
        posterUrl: "https://resizing.flixster.com/RxGQ1fzthgCQ0P2XMLVm675mK7c=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vUlRUVjQ1NTIwMC53ZWJw",
      },
    ],
    soundtrack: [
      {
        id: "game-of-thrones-season-1-soundtrack",
        noSeason: 1,
        noImage: true,
      },
      {
        id: "game-of-thrones-season-2-soundtrack",
        noSeason: 2,
        noImage: true
      },
      {
        id: "game-of-thrones-season-3-soundtrack",
        noSeason: 3,
        noImage: true
      },
      {
        id: "game-of-thrones-season-4-soundtrack",
        noSeason: 4,
        noImage: true
      },
      {
        id: "game-of-thrones-season-5-soundtrack",
        noSeason: 5,
        noImage: true
      },
      {
        id: "game-of-thrones-season-6-soundtrack",
        noSeason: 6,
        noImage: true
      },
      {
        id: "game-of-thrones-season-7-soundtrack",
        noSeason: 7,
        noImage: true
      },
      {
        id: "game-of-thrones-season-8-soundtrack",
        noSeason: 8,
        noImage: true
      },
    ],
    country: "US",
    language: "English",
    numberOfSeasons: 8,
    numberOfEpisodes: 73,
    executive: [
      "David Benioff",
      "D. B. Weiss",
      "George R. R. Martin",
      "Carolyn Strauss",
      "Frank Doelger",
      "Bernadette Caulfield",
      "Bryan Cogman",
      "Miguel Sapochnik",
      "David Nutter",
    ],
    producer: [
      "Mark Huffam",
      "Joanna Burn",
      "Chris Newman",
      "Greg Spence",
      "Lisa McAtackney",
      "Duncan Muggoch",
    ],
    prodLocation: [
      "United Kingdom",
      "Croatia",
      "Iceland",
      "Spain",
      "Malta",
      "Morocco",
      "Canada",
    ],
    prodCompanies: [
      "HBO Entertainment",
      "Television 360",
      "Grok! Television",
      "Generator Entertainment",
      "Startling Television",
      "Bighead Littlehead",
    ],
    network: "HBO",
    firstAirDate: "April 17, 2011", 
    lastAirDate: "May 19, 2019",
    tags: [
      "Action",
      "Adventure",
      "Fantasy",
      "Tragedy",
    ],
    related: [
      {
        id:"house-of-the-dragon", 
        title: "House of the Dragon", 
        posterUrl: "https://m.media-amazon.com/images/M/MV5BOWU2ZDA0M2EtNWEyYy00MWUwLWI4NjAtYzkxMDFjYzZkNGFiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
      },
      {
        id: "a-knight-of-the-seven-kingdoms",
        title: "A Knight of the Seven Kingdoms",
        posterUrl: "https://m.media-amazon.com/images/M/MV5BYzg4M2U3YWMtMWY4MS00MzFkLTk2ZWQtOThiOGYxZDEyMGQ2XkEyXkFqcGc@._V1_.jpg",
      }
    ],
 },
  {
    id:"bleach-thousand-year-blood-war", 
    title: "Bleach: Thousand-Year Blood War", 
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMjgyM2QzMjAtOGZjOS00OGFkLTkxZGYtMDJjZGM5MzIzYmM3XkEyXkFqcGc@._V1_.jpg",
    firstAirDate: "2022",
    tags: [
      "Adventure",
      "Martial arts",
      "Supernatural",
    ]
  },
  {
    id:"stuart-fails-to-save-the-universe", 
    title: "Stuart Fails to Save the Universe", 
    posterUrl: "https://resizing.flixster.com/OcTqg5V8FXrBe_dEBrcNbwsLAp4=/ems.cHJkLWVtcy1hc3NldHMvdHZzZXJpZXMvNmIxNDdhYzYtMGY3ZS00NTc4LWIwY2QtMjYzY2VjMDE5MmM4LmpwZw==",
    firstAirDate: "2026",
    tags: [
      "Comedy",
      "Science fiction",
      "Action-adventure",
    ]
  },
  {
    id:"house-of-the-dragon", 
    title: "House of the Dragon", 
    posterUrl: "https://m.media-amazon.com/images/M/MV5BOWU2ZDA0M2EtNWEyYy00MWUwLWI4NjAtYzkxMDFjYzZkNGFiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    firstAirDate: "2022",
    tags: [
      "Action",
      "Adventure",
      "Fantasy",
      "Serial drama",
    ],
  },
  {
    id: "teen-wolf",
    title: "Teen Wolf",
    plot: "After being bitten by a werewolf, a shy teen gains new abilities and is drawn into supernatural conflicts. With his friends, he tries to protect his town while keeping his new life a secret.",
    tags: ["Supernatural", "Teen drama", "Mystery", "Thriller"],
    firstAirDate: "June 5, 2011",
    lastAirDate: "September 24, 2017",
    status: "Ended",
    language: "en",
    country: "US",
    posterUrl:
      "https://static0.srcdn.com/wordpress/wp-content/uploads/2024/11/teen-wolf-poster.jpg?q=49&fit=contain&w=480&dpr=2",
    numberOfSeasons: 6,
    numberOfEpisodes: 100,
    mainCharacters: [
      {
        id: "scott-mccall",
        firstName: "Scott",
        lastName: "McCall",
        imageUrl:
          "https://preview.redd.it/daily-character-discussion-scott-mccall-v0-6jd0q429ckbb1.jpg?width=300&format=pjpg&auto=webp&s=0f6b129244017bafafdd1fbce8d1e2590d8ec913",
        promo: true,
      },
      {
        id: "allison-argent",
        firstName: "Allison",
        lastName: "Argent",
        imageUrl:
          "https://i.pinimg.com/736x/c9/ef/8f/c9ef8f8e7fc740e9050bd1375fbabcb4.jpg",
        promo: true,
      },
      {
        id: "stiles-stilinski",
        firstName: "Stiles",
        lastName: "Stilinski",
        imageUrl: "https://s1.r29static.com/bin/entry/c9d/x/1728758/image.png",
        promo: true,
      },
      {
        id: "derek-hale",
        firstName: "Derek",
        lastName: "Hale",
        imageUrl:
          "https://i.pinimg.com/736x/02/66/f7/0266f73427e64a58ea542ab47b9ab3e4.jpg",
        promo: true,
      },
      {
        id: "lydia-martin",
        firstName: "Lydia",
        lastName: "Martin",
        imageUrl: "https://i.ebayimg.com/images/g/ou0AAOSwzDBbEjWk/s-l960.webp",
        promo: true,
      },
      {
        id: "malia-tate",
        firstName: "Malia",
        lastName: "Tate",
        imageUrl:
          "https://i.pinimg.com/736x/7c/53/54/7c5354dde51080c497ff947ed4bfc8e0.jpg",
        promo: true,
      },
      {
        id: "kira-yukimura",
        firstName: "Kira",
        lastName: "Yukimura",
        imageUrl:
          "https://preview.redd.it/lets-talk-about-kira-v0-a2036yj34ref1.jpg?width=600&format=pjpg&auto=webp&s=b7f8094de5a1d781e1c6de702a83dafbcf2c2c5a",
        promo: true,
      },
      {
        id: "liam-dunbar",
        firstName: "Liam",
        lastName: "Dunbar",
        imageUrl:
          "https://i.redd.it/daily-character-discussion-liam-dunbar-v0-7bdmcu6rwd9b1.jpg?width=405&format=pjpg&auto=webp&s=af184877268b34b9b3986ff35125e7aa1627d287",
        promo: true,
      },
      {
        id: "noah-stilinski",
        firstName: "Noah",
        lastName: "Stilinski",
        imageUrl: "/images/Teen Wolf/Noah.jpg",
        promo: true,
        nickname: ["Sheriff Stilinski"],
      },
      {
        id: "melissa-mccall",
        firstName: "Melissa",
        lastName: "McCall",
        imageUrl:
          "https://preview.redd.it/whats-you-favorite-melissa-mccall-quote-v0-k4wozl4uy2be1.jpeg?auto=webp&s=89664668cb6f0f4a64f1fe217b65d5d1d290e3e3",
        promo: false,
      },
      {
        id: "chris-argent",
        firstName: "Chris Argent",
        imageUrl:
          "https://i.pinimg.com/originals/58/fa/a8/58faa89c08dc8d6df89e787cfeb9a12f.jpg",
        promo: true,
      },
    ],
    cast: [
      { actor: "Tyler Posey", character: "Scott McCall" },
      { actor: "Crystal Reed", character: "Allison Argent" },
      { actor: "Dylan O'Brien", character: "Stiles Stilinski" },
      { actor: "Tyler Hoechlin", character: "Derek Hale" },
      { actor: "Holland Roden", character: "Lydia Martin" },
      { actor: "Colton Haynes", character: "Malia Tate" },
      { actor: "Arden Cho", character: "Kira Yukimura" },
      { actor: "Dylan Sprayberry", character: "Liam Dunbar" },
      { actor: "Linden hby", character: "Sheriff Noah Stilinski" },
      { actor: "Melissa Ponzio", character: "Melissa McCall" },
      { actor: "JR Bourne", character: "Chris Argent" },
    ],
    seasons: [
      {
        id: "teen-wolf-season-1",
        seasonNumber: 1,
        premiereDate:  "2011-06-05" ,
        finaleDate:  "August 15, 2011" ,
        premiereEpisode: "Wolf Moon",
        finaleEpisode: "Code Breaker",
        title: "Teen Wolf, Season 1",
        posterUrl: "https://m.media-amazon.com/images/I/41TxA3B-+0L.jpg",
        episodeCount: 12,
      },
      {
        id: "teen-wolf-season-2",
        seasonNumber: 2,
        premiereDate:  "2012-06-03" ,
        finaleDate:  "August 13, 2012" ,
        premiereEpisode: "Omega",
        finaleEpisode: "Master Plan",
        title: "Teen Wolf, Season 2",
        posterUrl:
          "https://m.media-amazon.com/images/I/81gUN66t3zL._AC_SL1500_.jpg",
        episodeCount: 12,
      },
      {
        id: "teen-wolf-season-3",
        seasonNumber: 3,
        premiereDate:  "2013-06-03" ,
        finaleDate:  "2014-03-24" ,
        premiereEpisode: "Tattoo",
        finaleEpisode: "The Divine Move",
        title: "Teen Wolf, Season 3",
        posterUrl:
          "https://m.media-amazon.com/images/I/81gUN66t3zL._AC_UF894,1000_QL80_.jpg",
        episodeCount: 24,
      },
      {
        id: "teen-wolf-season-4",
        seasonNumber: 4,
        premiereDate:  "2014-06-23" ,
        finaleDate:  "September 08, 2014" ,
        premiereEpisode: "The Dark Moon",
        finaleEpisode: "Smoke and Mirrors",
        title: "Teen Wolf, Season 4",
        posterUrl:
          "https://m.media-amazon.com/images/I/81Nd92tXkZL._AC_UF894,1000_QL80_.jpg",
        episodeCount: 12,
      },
      {
        id: "teen-wolf-season-5",
        seasonNumber: 5,
        premiereDate:  "2015-06-29" ,
        finaleDate:  "2016-03-08" ,
        premiereEpisode: "Creatures of the Night",
        finaleEpisode: "Apotheosis",
        title: "Teen Wolf, Season 5",
        posterUrl:
          "https://m.media-amazon.com/images/I/7174udHnWpL._AC_UF894,1000_QL80_.jpg",
        episodeCount: 20,
      },
      {
        id: "teen-wolf-season-6",
        seasonNumber: 6,
        premiereDate:  "2016-11-15" ,
        finaleDate:  "September 24, 2017" ,
        premiereEpisode: "Memory Lost",
        finaleEpisode: "The Wolves of War",
        title: "Teen Wolf, Season 6",
        posterUrl:
          "https://m.media-amazon.com/images/I/71s2W4wx65L._AC_UF894,1000_QL80_.jpg",
        episodeCount: 20,
      },
    ],
    soundtrack: [
      {
        id: "teen-wolf-season-1-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 1,
      },
      {
        id: "teen-wolf-season-2-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 2,
      },
      {
        id: "teen-wolf-season-3-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 3,
      },
      {
        id: "teen-wolf-season-4-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 4,
      },
      {
        id: "teen-wolf-season-5-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 5,
      },
      {
        id: "teen-wolf-season-6-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 6,
      },
    ],
    basedOn: true,
    composer: ["Jeff Davis"],
    creator: ["Dino Meneghin"],
    producer: [
      "Eric Wallace",
      "Graham Vanderbilt",
      "Blaine Williams",
      "Tyler Posey",
      "Ross Maxwell",
    ],
    executive: [
      "Jeff Davis",
      "Marty Adelstein",
      "René Echevarria",
      "Michael Thorn",
      "Tony DiSanto",
      "Liz Gateley",
      "Russell Mulcahy",
      "Joseph P. Genier",
      "Tim Andrew",
    ],
    prodLocation: ["Atlanta, Georgia", "Los Angeles, California"],
    prodCompanies: [
      "Adelstein Productions",
      "DiGa Vision",
      "First Cause, Inc.",
      "Lost Marbles Television",
      "Siesta Productions",
      "MTV Production Development",
      "MGM Television",
    ],
    network: ["MTV"],
    related: [
      {
        id: "teen-wolf-1985-film",
        title: "Teen Wolf (1985 film)",
        posterUrl: "https://m.media-amazon.com/images/M/MV5BMzNmYWJkMzktNGUxMS00ZGY1LTllNTAtNGY3YTg1YjliM2Q3XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
      },
      {
        id: "teen-wolf-too",
        title: "Teen Wolf Too",
        posterUrl: "https://upload.wikimedia.org/wikipedia/en/6/60/Teen_wolf_too.jpg?utm_source=en.wikipedia.org&utm_campaign=index&utm_content=original"
      },
      {
        id: "teen-wolf-1986-series",
        title: "Teen Wolf (1986 TV series)",
        posterUrl: "https://m.media-amazon.com/images/M/MV5BMzVmODAzMGQtMWQ1My00YjQ2LWE3ZDYtYWU0YjA1MmJiZjk3XkEyXkFqcGc@._V1_.jpg",
      },
      {
        id: "teen-wolf-the-movie",
        title: "Teen Wolf: The Movie",
        posterUrl: "https://m.media-amazon.com/images/M/MV5BZjZhOTliNTMtZGVlOS00NDgwLWE5MzctM2VlNTY1OWE3YzRiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg"
      },
    ],
  },
  {
    id:"supernatural", 
    title: "Supernatural", 
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMzJhNDk0MGUtMWI0YS00ZGFmLWE3OTktZTMwNjhlZjExNWZhXkEyXkFqcGc@._V1_.jpg",
    firstAirDate:"2005", 
    lastAirDate: "2020",
    tags: [ 	
      "Dark fantasy",
      "Action-adventure",
      "Melodrama",
    ]
  },
  {
    id:"attack-on-titan", 
    title: "Attack on Titan", 
    posterUrl: "https://m.media-amazon.com/images/I/81NCTgKhW9L._AC_UF1000,1000_QL80_.jpg",
    firstAirDate:"2013", 
    lastAirDate: "2023",
    tags: [
      "Action",
      "Dark fantasy",
      "Post-apocalyptic",
    ]
  },
  {
    id:"merlin-series",
    title: "Merlin", 
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNmI5NDgyZmQtNDc3YS00Mjg0LThmMzEtZjcyNzczOTJlYWY4XkEyXkFqcGc@._V1_.jpg",
    firstAirDate: "2008",
    lastAirDate: "2012",
    tags: [
      	"Medieval fantasy",
        "Adventure",
    ]
  },
{
    id: "stranger-things",
    title: "Stranger Things",
    posterUrl:
      "https://resizing.flixster.com/0xxuABVVuzJrUT130WFHKE-irEg=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vNzUyMTFhOTktZTU4Ni00ODkyLWJlYjQtZTgxYTllZmU2OGM0LmpwZw==",
    country: "US",
    language: "En",
    firstAirDate: "July 15, 2016",
    lastAirDate: "January 1, 2026",
    status: "Ended",
    numberOfSeasons: 5,
    numberOfEpisodes: 42,
    tags: ["drama", "netflix", "teens", "mystery"],
    plot: "When a boy vanishes in a small town, his friends uncover secret experiments, supernatural forces, and a mysterious girl with powers—opening a doorway to another world.",
    mainCharacters: [
      {
        id: "eleven",
        firstName: "Eleven",
        lastName: "",
        imageUrl: "https://preview.redd.it/happy-birthday-to-our-eleven-10-millie-bobby-brown-v0-ig0uqyhn65ja1.gif?format=png8&s=c24dd6d2896f5bf926b027da6730404354f6943f",
        posterUrl: "https://pbs.twimg.com/media/FS5XuDqWAAE3X8k?format=jpg&name=900x900",
        promo: true,
      },
      {
        id: "mike-wheeler",
        firstName: "Mike",
        lastName: "Wheeler",
        imageUrl: "https://static0.colliderimages.com/wordpress/wp-content/uploads/2026/01/strange-things-finale-mike.jpg?w=1200&h=675&fit=crop",
        posterUrl: "https://preview.redd.it/lock-this-prediction-in-guys-mike-wheeler-will-die-in-v0-fjp4tvslcq1g1.jpeg?width=1080&crop=smart&auto=webp&s=f4190eea000864b6da56b20ff0fe0ac6e1a569d0",
        promo: true,
      },
      {
        id: "dustin-henderson",
        firstName: "Dustin",
        lastName: "Henderson",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeMt-XlqViokU38IgXP3yo65JtjSPmrF_t0EN-mpBMXemZbIqLkqpDu4E&s=10",
        posterUrl:  "https://preview.redd.it/realistically-following-spoiler-s-death-how-do-we-think-v0-l4jmlnnim48c1.jpeg?auto=webp&s=fc17e3bedc852c5e313748c549129b8b85a642f5",
        promo: true,
      },
      {
        id: "lucas-sinclair",
        firstName: "Lucas ",
        lastName: "Sinclair",
        imageUrl: "https://i.pinimg.com/736x/a2/49/81/a24981fc75a8c9faccb4f762860454b6.jpg",
        posterUrl: "https://pbs.twimg.com/media/G5C3RQUWcAE02DP?format=jpg&name=large",
        promo: true,
      },
      {
        id: "will-byers",
        firstName: "William",
        lastName: "Byers",
        imageUrl: "https://i.pinimg.com/736x/43/7e/63/437e6395e4ef156c70da4a24951ee60c.jpg",
        posterUrl: "https://hips.hearstapps.com/hmg-prod/images/will-stranger-things-season-4-1653571856.jpg?crop=0.799xw:0.540xh;0.0839xw,0.0304xh&resize=980:*",
        promo: true,
        nickname: ["Will"],
        goesByNickname: true,
      },
      {
        id: "nancy-wheeler",
        firstName: "Nancy",
        lastName: "Wheeler",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcFuTVcKUWB3_24i1JDfaRVO2zPjIoWXjK45s1c4sVi8oyoNqTAWerj8E&s=10",
        posterUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTXgC49ODKjMbO5WhTfH1VDQ7Tdm25RjnU043H3IfM4G10RX5sg",
        promo: true,
      },
      {
        id: "jonathan-byers",
        firstName: "Jonathan",
        lastName: "Byers",
        imageUrl: "https://i.pinimg.com/736x/1b/90/bb/1b90bb0a4cc3041361cdbdb877b7a284.jpg",
        posterUrl: "https://preview.redd.it/who-do-you-guys-got-dying-almost-100-in-season-5-v0-ntff0h42bcgf1.jpeg?auto=webp&s=e5c729af59044159e1a57936d5aa9c01fcc9f16e",
        promo: true,
      },
      {
        id: "karen-wheeler",
        firstName: "Karen",
        lastName: "Wheeler",
        imageUrl: "https://static.wikia.nocookie.net/strangerthings8338/images/0/05/Karen_s5.png/revision/latest/smart/width/300/height/300?cb=20251128114405", 
        posterUrl: "https://i.redd.it/a7udb90jzkzf1.jpeg",
        promo: true,
      },
      {
        id: "martin-brenner",
        firstName: "Martin",
        lastName: "Brenner",
        imageUrl: "https://static.wikia.nocookie.net/strangerthings8338/images/b/be/Brenner_S1.png/revision/latest/smart/width/300/height/300?cb=20221115135716",
        posterUrl: "https://preview.redd.it/opinions-on-martin-brenner-as-a-character-villain-v0-ez1zfvzmcmia1.jpg?auto=webp&s=08c110b5bff109f9bedce85ef5df0e704bedb01c",
        promo: true,
        nickname: ["Dr. Brenner"],
        goesByNickname: true,
      },
      {
        id: "max-mayfield",
        firstName: "Maxine",
        lastName: "Mayfield",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRk1sVQuzB0emAkre5Dnjscfx1t8hTK61DC5l71PF4pHdWhhGGXIT24xu8&s=10",
        posterUrl: "https://pbs.twimg.com/media/G69hQIbXwAEzxHd?format=jpg&name=large",
        promo: true,
        nickname: ["Max"],
        goesByNickname: true,
      },
      {
        id: "steve-harrington",
        firstName: "Steven",
        lastName: "Harrington",
        imageUrl: "https://media.allure.com/photos/59f355a64921eb420a913a69/1:1/w_3720,h_3720,c_limit/wv_publicity_pre_launch_A_still_40.000001R.jpeg", 
        posterUrl: "https://images.thedirect.com/media/photos/steves.jpg",
        promo: true,
        nickname: ["Steve"],
        goesByNickname: true,
      },
      {
        id: "robin-buckley",
        firstName: "Robin",
        lastName: "Buckley",
        imageUrl: "https://i1.sndcdn.com/artworks-z6mk5ayqRU3QGizj-lvxL9A-t500x500.jpg",
        posterUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiGQBvALn2aTH1ff1SMLSJ7G7w-DH-Jdaf295h1ye7ArPiVoZP",
        promo: true,
      },
      {
        id: "billy-hargrove",
        firstName: "William",
        lastName: "Hargrove",
        imageUrl: "https://media.vanityfair.com/photos/59f49b5220586235aaecf93b/1:1/w_3681,h_3681,c_limit/wv_publicity_pre_launch_A_still_7.000001.jpeg",
        posterUrl: "https://assets.change.org/photos/9/ji/ey/MpjieYqjSjSJUGW-1600x900-noPad.jpg?1563395498",
        promo: true,
        nickname: ["Billy"],
        goesByNickname: true
      },
      {
        id: "bob-newby",
        firstName: "Robert",
        lastName: "Newby",
        imageUrl: "https://i.pinimg.com/736x/fa/ef/b3/faefb3a6385a519cbf1daa375590e44b.jpg",
        posterUrl: "https://i.redd.it/nk30b23cnn141.png",
        promo: true,
        nickname: ["Bob"],
        goesByNickname: true,
      },
      {
        id: "dr.-sam owens",
        firstName: "Samuel",
        lastName: "Owens",
        imageUrl:
          "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2023/04/stranger-things-sam-owens.jpg?q=50&fit=crop&w=825&dpr=1.5",
        promo: true,
        nickname: ["Sam"],
      },
      {
        id: "erica-sinclair",
        firstName: "Erica",
        lastName: "Sinclair",
        imageUrl: "https://i.pinimg.com/736x/ab/07/28/ab072811bffbbca1d642d73164d46668.jpg",
        posterUrl: "https://i.namu.wiki/i/KX35S683vYCvEYBsM1B9awIzFlSK-M4uHMyr0YvfRAbixwNdKQ5Avzfnnila_pvGhtRBr-tn35ZUWhnPmsSS4g.webp",
        promo: true,
      },
      {
        id: "murray-bauman",
        firstName: "Murray",
        lastName: "Bauman",
        imageUrl: "https://static.wikia.nocookie.net/strangerthings8338/images/d/dd/Murray2.jpg/revision/latest/smart/width/300/height/300?cb=20201103150557",
        posterUrl: "https://preview.redd.it/whats-your-opinion-on-murray-v0-170nejcuxtba1.png?auto=webp&s=095cf7e18e9a3d41505df5d5338f48e3c63da984",
        promo: true,
      },
      {
        id: "dr-kay",
        lastName: "Kay",
        imageUrl: "https://cdn.mos.cms.futurecdn.net/RQyWsaKTAKNjpksJFgjQBh.jpg",
        posterUrl:"https://pbs.twimg.com/media/G9noTBvbIAA4Oeh?format=jpg&name=900x900",
        promo: true,
        nickname: ["Dr. Kay"],
        goesByNickname: true,
      },
      {
        id: "henry-creel",
        firstName: "Henry",
        lastName: "Creel",
        imageUrl:
          "https://preview.redd.it/vecnas-vision-v0-f44uvni8e31c1.jpg?auto=webp&s=2919d4f6232706aacb3c51d63131d3515f5e6a7d",
        promo: true,
        nickname: ["Vecna"],
        goesByNickname: true,
      },
    ],
    cast: [
      { actor: "Millie Bobby Brown", character: "Eleven" },
      { actor: "Finn Wolfhard", character: "Mike Wheeler" },
      { actor: "Gaten Matarazzo", character: "Dustin Henderson" },
      { actor: "Caleb McLaughlin", character: "Lucas Sinclair" },
      { actor: "Noah Schnapp", character: "Will Byers" },
      { actor: "Natalia Dyer", character: "Nancy Wheeler" },
      { actor: "Charlie Heaton", character: "Jonathan Byers" },
      { actor: "Cara Buono", character: "Karen Wheeler " },
      { actor: "Matthew Modine", character: "Dr. Martin Brenner " },
      { actor: "Noah Schnapp", character: "Will Byers " },
      { actor: "Sadie Sink", character: "Max Mayfield " },
      { actor: "Joe Keery", character: "Steve Harrington " },
      { actor: "Dacre Montgomery", character: "Billy Hargrove " },
      { actor: "Sean Astin", character: "Bob Newby " },
      { actor: "Paul Reiser", character: "Dr. Sam Owens " },
      { actor: "Maya Hawke", character: "Robin Buckley " },
      { actor: "Priah Ferguson", character: "Erica Sinclair " },
      { actor: "Brett Gelman", character: "Murray Bauman " },
      { actor: "Linda Hamilton", character: "Dr. Kay " },
      {
        actor: "Jamie Campbell Bower",
        character: "Henry Creel / One / Vecna ",
      },
      { actor: "Nell Fisher (season 5) ", character: "Holly Wheeler" },
      {
        actor: "Anniston and Tinsley Price (co-star: seasons 1–4)",
        character: "Holly Wheeler",
      },
    ],
    seasons: [
      {
        id: "stranger-things-season-1",
        seasonNumber: 1,
        premiereDate:  "July 15, 2016" ,
        premiereEpisode: "Chapter One: The Vanishing of Will Byers",
        finaleEpisode: "Chapter Eight: The Upside Down",
        title: "Stranger Things, Season 1",
        posterUrl:
          "https://i.ebayimg.com/images/g/8YcAAOSw-K9ZLtaa/s-l1600.webp",
        episodeCount: 8,
      },
      {
        id: "stranger-things-season-2",
        seasonNumber: 2,
        premiereDate:  "2017-10-27" ,
        premiereEpisode: "Chapter One: MADMAX",
        finaleEpisode: "Chapter Nine: The Gate",
        title: "Stranger Things, Season 2",
        posterUrl:
          "https://i.ebayimg.com/images/g/LK4AAOSwkZdgZEyl/s-l1600.webp",
        episodeCount: 9,
      },
      {
        id: "stranger-things-season-3",
        seasonNumber: 3,
        premiereDate:  "July 04, 2019" ,
        premiereEpisode: "Chapter One: Suzie, Do You Copy?",
        finaleEpisode: "Chapter Eight: The Battle of Starcourt",
        title: "Stranger Things, Season 3",
        posterUrl:
          "http://www.lisaschmoelzer.at/wp-content/uploads/2019/07/StrangerThingsPoster-692x1024.jpg",
        episodeCount: 8,
      },
      {
        id: "stranger-things-season-4",
        seasonNumber: 4,
        premiereDate:  "July 01, 2022" ,
        premiereEpisode: "Chapter One: The Hellfire Club",
        finaleEpisode: "Chapter Nine: The Piggyback",
        title: "Stranger Things, Season 4",
        posterUrl:
          "https://miro.medium.com/v2/resize:fit:720/format:webp/0*9qnmU5A1A-mSju2c",
        episodeCount: 9,
      },
      {
        id: "stranger-things-season-5",
        seasonNumber: 5,
        premiereDate:  "2025-11-26" ,
        finaleDate:  "2025-12-31" ,
        premiereEpisode: "Chapter One: The Crawl",
        finaleEpisode: "Chapter Eight: The Rightside Up",
        title: "Stranger Things, Season 5",
        posterUrl:
          "https://static.tvmaze.com/uploads/images/original_untouched/595/1489169.jpg",
        episodeCount: 8,
      },
    ],
    soundtrack: [
      {
        id: "stranger-things-season-1-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 1,
      },
      {
        id: "stranger-things-season-2-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 2,
      },
      {
        id: "stranger-things-season-3-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 3,
      },
      {
        id: "stranger-things-season-4-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 4,
      },
      {
        id: "stranger-things-season-5-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 5,
      },
      
    ],
    creator: ["The Duffer Brothers"],
    producer: ["Lampton Enochs"],
    executive: [
      "Karl Gajdusek",
      "Cindy Holland",
      "Brian Wright",
      "Matt Thunell",
      "Shawn Levy",
      "Dan Cohen",
      "The Duffer Brothers",
      "Iain Paterson",
      "Curtis Gwinn",
    ],
    prodLocation: ["Atlanta, Georgia"],
    prodCompanies: [
      "21 Laps Entertainment",
      "Monkey Massacre Productions (seasons 1–4)",
      "Upside Down Pictures (season 5)",
    ],
    network: ["Netflix"],
    related: [
      {
        id: "Stranger Things: Tales from '85",
        posterUrl: "https://m.media-amazon.com/images/M/MV5BMWU5NzgzY2QtNDVjZS00NDFkLThmMzctNTIzZmY5ZWYxZTE5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg"
      }, 
      ],
  }, 
   {
    id:"from", 
    title: "From", 
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNDAwNDljNWEtNWE1Zi00YjFlLWEzM2UtY2E3ZTM1MTcxMTcyXkEyXkFqcGc@._V1_.jpg",
    firstAirDate: "2022",
    tags: [
      "Science fiction",
      "Horror",
      "Mystery",
    ],
  },
  {
    id: "smallville",
    title: "Smallville",
    posterUrl:
      "https://i.ebayimg.com/00/s/MTYwMFgxMDc4/z/EgAAAOSw4h9lruPO/$_57.JPG?set_id=880000500F",
    country: "US",
    language: "En",
    firstAirDate: "October 16, 2001",
    lastAirDate: "May 11, 2006",
    status: "Ended",
    numberOfSeasons: 10,
    numberOfEpisodes: 218,
    tags: ["drama", "superhero", "high-school", "origin-story"],
    plot: "A teenage Clark Kent grows up in Smallville, learning to control his emerging powers while protecting the people he loves and facing threats that hint at his larger destiny.",
    mainCharacters: [
      {
        id: "clark-kent",
        firstName: "Clark",
        lastName: "Kent",
        imageUrl: "https://tvovermind.com/wp-content/uploads/2021/09/serie-smallville-ator-tom-welling-credito-divulgacao-the-cw-grande.jpg",
        posterUrl: "https://i.pinimg.com/736x/13/d9/03/13d903d03aaedc4dc62cad51fdbd894d.jpg",
        promo: true,
      },
      {
        id: "lana-lang",
        firstName: "Lana",
        lastName: "Lang",
        imageUrl: "https://i.ytimg.com/vi/4I-XDv3f6Ds/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLA-mimP1uAgVTogoADgdwEyeMeLTQ",
        posterUrl: "https://i.ebayimg.com/images/g/8FsAAOSwnsljvaWa/s-l1600.webp",
        promo: true,
      },
      {
        id: "lex-luthor",
        firstName: "Lex",
        lastName: "Luthor",
        imageUrl: "https://bleedingcool.com/wp-content/uploads/2024/02/lexluthorsmallville-1-2000x1125.jpg",
        posterUrl: "https://i.namu.wiki/i/I9C4uHAGeVd9Poo9phWmXTSsHFByp_ahK6G6jOq_-HyaEv063F-tXKBvZQ5xs4QaZDEkcyScnPdziVJmzenExg.webp",
        promo: true,
      },
      {
        id: "lois-lane",
        firstName: "Lois",
        lastName: "Lane",
        imageUrl: "https://i.redd.it/who-do-you-consider-the-female-lead-of-season-8-v0-d7o8rvoqo31g1.jpg?width=967&format=pjpg&auto=webp&s=357d836afdaf3e3c2fe2be9f1845496084a04648",
        posterUrl: "https://i.ebayimg.com/images/g/HywAAOSwRxpk1M8X/s-l1600.webp",
        promo: true,
      },
      {
        id: "chloe-sullivan",
        firstName: "Chloe",
        lastName: "Sullivan",
        imageUrl: "https://i.pinimg.com/736x/43/f8/56/43f856e57c186a9fbdd5ae5d83db2234.jpg",
         posterUrl: "https://i.pinimg.com/736x/bb/e3/b6/bbe3b69b5c23cb7464c218b8770bec9b.jpg",
        promo: true,
      },
      {
        id: "jonathan-kent",
        firstName: "Jonathan",
        lastName: "Kent",
        imageUrl: "https://i.pinimg.com/736x/71/9f/5c/719f5c6a9f98264d87c2ceead185c3f3.jpg",
        posterUrl: "https://photos1.blogger.com/blogger/7807/2295/1600/john%20schneider%202.jpg",
        promo: true,
      },
      {
        id: "martha-kent",
        firstName: "Martha",
        lastName: "Kent",
        imageUrl: "https://i.pinimg.com/564x/ba/82/16/ba82168d45cc64f2655b87e307be0c77.jpg",
        posterUrl: "https://static.hdrezka.ac/i/2016/6/23/kbc68e2144712zt15p65b.jpeg",
        promo: true,
      },
      {
        id: "lionel-luthor",
        firstName: "Lionel",
        lastName: "Luthor",
        imageUrl: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjyupBcDngSZ1h4_ZeM18UGeK3B7iKUSxjpQpyYFiIg4h3fIyqMGdODepGrcGN_ON2QeI_VTRosdTTsIdiKprqtw4sdT6ixVE98MYbuIjwafBW4yAvHRW1rqJP1bgOTjJaOqmiHoV8cjAvQmcEuP3HFel4GKV815tPvUNnN7l_pqb9DuIWaADwUXsHk/s1120/Smallville-108-Lionel-Luthor.jpg",
        posterUrl: "https://i.redd.it/1yzeok3nim2c1.jpg",
        promo: true,
      },
      {
        id: "pete-ross",
        firstName: "Peter",
        lastName: "Ross",
        imageUrl: "https://static.wikia.nocookie.net/superman/images/a/aa/Pete_Ross_-_Sam_Jones.jpg/revision/latest?cb=20160827172248",
        posterUrl: "https://static0.cbrimages.com/wordpress/wp-content/uploads/2025/09/sam-jones-iii-as-pete-ross-from-smallville.jpg?w=1200&h=628&fit=crop",
        promo: true,
        nickname: ["Pete"],
        goesByNickname: true,
      },
      {
        id: "henry-james-olsen",
        firstName: "Henry-James",
        lastName: "Olsen",
        imageUrl: "https://pbs.twimg.com/media/HITGXkYWkAAHdFp.jpg",
        posterUrl: "https://i.pinimg.com/736x/73/22/be/7322bee6bd6efba43384694e9060617b.jpg",
        promo: true,
        nickname: ["Jimmy"],
        goesByNickname: true
      },
      {
        id: "kara-kent",
        firstName: "Kara",
        lastName: "Kent",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBd-UCqJgosBqtZnol9d_tSe_q2q7xC8AyGnAkByD3cp4l4ZlhwYRHNi9m&s=10",
        posterUrl: "https://preview.redd.it/supergirl-laura-vandervoort-v0-akaex1edj20c1.jpg?width=1080&crop=smart&auto=webp&s=0cb4475b65f8a5ed24b0fb90682c350afc2e6140",
        promo: true,
      },
    ],
    cast: [
      { actor: "Tom Welling", character: "Clark Kent", creditOrder: 1 },
      { actor: "Kristin Kreuk", character: "Lana Lang", creditOrder: 2 },
      { actor: "Michael Rosenbaum", character: "Lex Luthor", creditOrder: 3 },
      { actor: "Erica Durance", character: "Lois Lane", creditOrder: 4 },
      { actor: "Allison Mack", character: "Chloe Sullivan", creditOrder: 5 },
    ],
    seasons: [
      {
        id: "smallville-season-1",
        seasonNumber: 1,
        premiereDate:  "2001-10-16" ,
        finaleDate:  "May 21, 2002" ,
        premiereEpisode: "Pilot",
        finaleEpisode: "Tempest",
        title: "Smallville, Season 1",
        posterUrl:
          "https://m.media-amazon.com/images/I/81aShIuryPL._AC_SL1500_.jpg",
        episodeCount: 21,
      },
      {
        id: "smallville-season-2",
        seasonNumber: 2,
        premiereDate:  "September 24, 2002" ,
        finaleDate:  "May 20, 2003" ,
        premiereEpisode: "Vortex",
        finaleEpisode: "Exodus",
        title: "Smallville, Season 2",
        posterUrl:
          "https://m.media-amazon.com/images/I/518qYq3I-wL._AC_UF894,1000_QL80_.jpg",
        episodeCount: 23,
      },
      {
        id: "smallville-season-3",
        seasonNumber: 3,
        premiereDate:  "2003-10-01" ,
        finaleDate:  "May 19, 2004" ,
        premiereEpisode: "Exile",
        finaleEpisode: "Covenant",
        title: "Smallville, Season 3",
        posterUrl:
          "https://m.media-amazon.com/images/I/91ffFyuGqjL._AC_SL1500_.jpg",
        episodeCount: 22,
      },
      {
        id: "smallville-season-4",
        seasonNumber: 4,
        premiereDate:  "September 22, 2004" ,
        finaleDate:  "May 18, 2005" ,
        premiereEpisode: "Crusade",
        finaleEpisode: "Commencement",
        title: "Smallville, Season 4",
        posterUrl:
          "https://m.media-amazon.com/images/I/916s4wnUeoL._AC_SL1500_.jpg",
        episodeCount: 22,
      },
      {
        id: "smallville-season-5",
        seasonNumber: 5,
        premiereDate:  "September 29, 2005" ,
        finaleDate:  "May 11, 2006" ,
        premiereEpisode: "Arrival",
        finaleEpisode: "Vessel",
        title: "Smallville, Season 5",
        posterUrl:
          "https://m.media-amazon.com/images/I/71zVXXpMhJL._AC_UF894,1000_QL80_.jpg",
        episodeCount: 22,
      },
      {
        id: "smallville-season-6",
        seasonNumber: 6,
        premiereDate:  "September 28, 2006" ,
        finaleDate:  "May 17, 2007" ,
        premiereEpisode: "Zod",
        finaleEpisode: "Phantom",
        title: "Smallville, Season 6",
        posterUrl:
          "https://m.media-amazon.com/images/I/71wVNVavUeL._AC_UF894,1000_QL80_.jpg",
        episodeCount: 22,
      },
      {
        id: "smallville-season-7",
        seasonNumber: 7,
        premiereDate:  "September 27, 2007" ,
        finaleDate:  "May 15, 2008" ,
        premiereEpisode: "Bizarro",
        finaleEpisode: "Arctic",
        title: "Smallville, Season 7",
        posterUrl:
          "https://i.ebayimg.com/images/g/A0EAAMXQU6tQ9xg3/s-l960.webp",
        episodeCount: 20,
      },
      {
        id: "smallville-season-8",
        seasonNumber: 8,
        premiereDate:  "September 18, 2008" ,
        finaleDate:  "May 14, 2009" ,
        premiereEpisode: "Odyssey",
        finaleEpisode: "Doomsday",
        title: "Smallville, Season 8",
        posterUrl:
          "https://m.media-amazon.com/images/I/91aIzoIil-L._AC_SL1500_.jpg",
        episodeCount: 22,
      },
      {
        id: "smallville-season-9",
        seasonNumber: 9,
        premiereDate:  "September 25, 2009" ,
        finaleDate:  "May 14, 2010" ,
        premiereEpisode: "Savior",
        finaleEpisode: "Salvation",
        title: "Smallville, Season 9",
        posterUrl:
          "https://m.media-amazon.com/images/I/613aP3zxrSL._AC_UF894,1000_QL80_.jpg",
        episodeCount: 21,
      },
      {
        id: "smallville-season-10",
        seasonNumber: 10,
        premiereDate:  "September 24, 2010" ,
        finaleDate:  "May 13, 2011" ,
        premiereEpisode: "Lazarus",
        finaleEpisode: "Finale",
        title: "Smallville, Season 10",
        posterUrl:
          "https://media.themoviedb.org/t/p/w500/nUiw76eCg1uT8uz5Ibtu6FWYlgX.jpg",
        episodeCount: 22,
      },
    ],
    soundtrack: [
      { 
        id: "smallville-season-1",
        type: "soundtrack",
        noImage: true,
        noSeason: 1,
      },
      { 
        id: "smallville-season-2-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 2,
      },
      { 
        id: "smallville-season-3-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 3,
      },
      { 
        id: "smallville-season-4-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 4,
      },
      { 
        id: "smallville-season-5-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 5,
      },
      { 
        id: "smallville-season-6-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 6,
      },
      { 
        id: "smallville-season-7-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 7,
      },
      { 
        id: "smallville-season-8-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 8,
      },
      { 
        id: "smallville-season-9-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 9,
      },
      { 
        id: "smallville-season-10-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 10,
      },
    ],
    themeSong: ["'We Used to Be Friends' by The Dandy Warhols"],
    creator: ["Rob Thomas"],
    narrator: ["Kristen Bell"],
    producer: [
      "Tom Flores",
      "Robert Hargrove",
      "Jeph Loeb",
      "Mark D. Warshaw",
      "David Willson",
      "Christopher Petry",
      "Holly Henderson",
      "Don Whitehead",
      "Scott Graham",
      "Cristina Verano",
      "Anne Cofell Saunders",
      "Jordan Hawley",
      "Philip Levens",
      "Luke Schelhaas",
      "Doris Egan",
      "Michael Green",
      "Greg Walker",
      "Holly Harold",
      "Juanita Diana Feeney",
      "Robert Petrovicz",
      "Tim Iacofano",
      "David Nutter",
    ],
    executive: [
      "David Nutter (Pilot)",
      "Alfred Gough",
      "Miles Millar",
      "Michael Tollin",
      "Brian Robbins",
      "Joe Davola",
      "Ken Horton",
      "Greg Beeman",
      "James March hall",
      "Todd Slavkin",
      "Darren Swimmer",
      "Kelly Souders",
      "Brian Peterson",
      "Tom Welling",
    ],
    prodLocation: ["British Columbia, Canada"],
    prodCompanies: [
      "Tollin/Robbins Productions",
      "Millar Gough Ink",
      "DC Entertainment",
      "Warner Bros. Television",
    ],
    network: ["The WB", "The CW"],
    
  },
  
  {
    id:"outlander", 
    title: "Outlander", 
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMTc4M2JmYmEtMjJhOC00MmRlLThhZDEtMWRhZTZiNTI0ZDZhXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    firstAirDate: "2014",
    lastAirDate: "2026",
    tags: [
      	
      "Historical fantasy",
      "Drama",
      "Adventure",
      "Romantic fantasy",
      "Fantasy"
    ]
  },
  {
    id:"heroes",
    title: "Heroes", 
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMjI3ODU0OTQ1MV5BMl5BanBnXkFtZTgwNzI0MTQ2MzE@._V1_.jpg",
    firstAirDate: "2006", 
    lastAirDate: "2010",
    tags: [ 	
      "Superhero",
      "Drama",
    ]
  },
  {
    id:"supergirl", 
    title: "Supergirl", 
    firstAirDate: "2015",
    lastAirDate: "2021",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BZGM4MzY3NzYtYjViZS00MmE4LTgxZmMtNTZkNDM5MDIwMDg1XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    tags: [
      "Action",
      "Drama",
      "Political",
      "Science fiction",
      "Superhero",
    ]
  },
  {
    id:"arrow", 
    title: "Arrow", 
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNjRlNjNlY2YtYzQxNS00ZTUzLTkwMTQtMjM0YjZlOWQwZmFkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    firstAirDate: "2012",
    lastAirDate: "2020",
    tags: [
      "Action",
      "Crime",
      "Drama",
      "Mystery",
      "Superhero",
    ]
  },
  {
    id:"lost", 
    title:"Lost",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BZmZhY2ViYzYtMTQ0NS00NDcyLWIxZTYtMGUyODE0NDA0NmNkXkEyXkFqcGc@._V1_.jpg", 
    firstAirDate: "2004", 
    lastAirDate:"2010",
    tags: [	
      "Adventure",
      "Hybrid",
      "Mystery",
      "Science fiction",
      "Serial drama",
      "Supernatural",
      "Survival",
      "Thriller",
    ]
  },
  {
    id:"once-upon-a-time", 
    title:"Once Upon A Time", 
    posterUrl: "https://m.media-amazon.com/images/M/MV5BZDgwNTcwYmMtNjVmNi00NDdkLTllY2MtYmQ4MTM3ZThjZTllXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    firstAirDate: "2014", 
    lastAirDate:"2026",
    tags: [	
      "Adventure",
      "Drama",
      "Fantasy",
    ]
  },
  {
    id:"fringe", 
    title:"Fringe", 
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMWVlMmE1MmEtNjhjMC00MDdmLWIzZGMtNjc1YTZmNDc2MWExXkEyXkFqcGc@._V1_.jpg",
    firstAirDate: "2008",
    lastAirDate: "2013",
    tags: [ 	
      "Drama",
      "Science fiction",
      "Paranormal fiction",
    ]
},
  {
    id:"grimm", 
    title:"Grimm", 
    posterUrl: "https://image.tmdb.org/t/p/original/iOptnt1QHi6bIHmOq6adnZTV0bU.jpg",
    firstAirDate: "2011",
    lastAirDate: "2017",
    tags: [
      "Occult detective fiction",
      "Police procedural",
      "Horror",
      "Supernatural",
      "Fantasy",
    ]

  },
{
    id: "the-vampire-diaries",
    title: "The Vampire Diaries",
    plot: "A teen girl’s life is turned upside down when two vampire brothers return to her town, pulling her into a world of supernatural politics, romance, and danger.",
    tags: ["Supernatural", "Teen drama", "Romance", "Drama"],
    firstAirDate: "September 10, 2009",
    lastAirDate: "March 10, 2017",
    status: "Ended",
    language: "en",
    country: "US",
    posterUrl:
      "https://static1.srcdn.com/wordpress/wp-content/uploads/2022/11/The-Vampire-Diaries-New-Poster.jpg",
    numberOfSeasons: 8,
    numberOfEpisodes: 171,
    mainCharacters: [
      {
        id: "elena-gilbert",
        firstName: "Elena",
        lastName: "Gilbert",
        imageUrl: "https://i.redd.it/xb4t1scierv91.jpg",
        posterUrl:  "https://preview.redd.it/almost-done-with-season-6-and-feel-like-elena-wasnt-even-a-v0-1o0lsxjttckd1.jpeg?auto=webp&s=5a34a469d2a7fe65d156da6ef5057b5a3c572ea2",
        promo: true,
      },
      {
        id: "stefan-salvatore",
        firstName: "Stefan",
        lastName: "Salvatore",
        imageUrl: "https://static.wikia.nocookie.net/vampires/images/a/ae/I-would-die-for-stefan-salvatore-v0-ywjftkrjl2d81.jpg/revision/latest?cb=20240715135421",
        posterUrl:  "https://www.tvline.com/tvline/interviews/vampire-diaries-caroline-stefan-elena-spoilers-season-6-581800/vampire-diaries-stefan.jpg",
        promo: true,
      },
      {
        id: "damon-salvatore",
        firstName: "Damon",
        lastName: "Salvatore",
        imageUrl: "https://preview.redd.it/damons-redemption-v0-etkw930gn67g1.jpeg?width=1080&crop=smart&auto=webp&s=a1241d6b8c9d12b3249a9f1c165d706b1331b2b6",
        posterUrl: "https://i.ebayimg.com/images/g/6PEAAOSwqu9VQM8W/s-l1200.jpg",
        promo: true,
      },
      {
        id: "jeremy-gilbert",
        firstName: "Jeremy",
        lastName: "Gilbert",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCzthpmTIrxXJRIJTv2DSXezIi_LwJY2c2eGSpMlOlx0GXShBlh0dhvCE&s=10",
        posterUrl: "https://static1.purebreak.com.br/articles/9/16/67/9/@/83128-steven-r-mcqueen-o-jeremy-de-the-580x0-3.jpg",
        promo: true,
      },
      {
        id: "bonnie-bennett",
        firstName: "Bonnie",
        lastName: "Bennett",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7DajCOgLu0_HzV59KjYJchxqjDU-GEHx5KKKBK8R2JRvuhmLy98SjB0U&s=10",
        posterUrl: "https://static.wikia.nocookie.net/p__/images/a/a4/Bonnie_Bennett_Season_6.jpg/revision/latest?cb=20141101190715&path-prefix=",
        promo: true,
      },
      {
        id: "caroline-forbes",
        firstName: "Caroline",
        lastName: "Forbes",
        imageUrl: "https://preview.redd.it/we-listen-and-we-dont-judge-caroline-forbes-edition-v0-kpmlbztqweae1.jpeg?width=640&crop=smart&auto=webp&s=983673ecf9946f39e8ce1e2c9012a0ac5cb39185",
        posterUrl: "https://pbs.twimg.com/media/ELOnEprWoAE4eDd.jpg",
        promo: true,
      },
      {
        id: "tyler-lockwood",
        firstName: "Tyler",
        lastName: "Lockwood",
        imageUrl: "https://preview.redd.it/why-was-tyler-in-season-6-he-was-the-most-useless-character-v0-lxpikxnzezcb1.jpg?width=640&crop=smart&auto=webp&s=1fc92d228f83176d96b392ba24f321aa2ca3c536",
        posterUrl: "https://static.wikia.nocookie.net/p__/images/f/f1/Tyler_Lockwood_Season_6.jpg/revision/latest?cb=20141101191844&path-prefix=",
        promo: true,
      },
      {
        id: "alaric-saltzman",
        firstName: "Alaric",
        lastName: "Saltzman",
        imageUrl: "https://i.pinimg.com/474x/2d/08/90/2d08907e9514e218fc2b76beaf51c5a3.jpg",
        posterUrl: "https://i.redd.it/4ijaozomtbj61.jpg",
        promo: true,
      },
      {
        id: "klaus-mikaelsson",
        firstName: "Klaus",
        lastName: "Mikaelsson",
        imageUrl: "https://preview.redd.it/klaus-season-3-of-tvd-is-peak-male-attractiveness-for-me-v0-c58m67yv1zoe1.jpg?width=640&crop=smart&auto=webp&s=c4dc86c6807e1f0cceab3807dfcc8c47bca4524d",
        posterUrl:  "https://i.pinimg.com/564x/86/e3/8b/86e38bcd137155b9325cdf41dc6a9f95.jpg",
        promo: true,
      },
      {
        id: "enzo-st-john",
        firstName: "Lorenzo",
        lastName: "St. John",
        imageUrl: "https://pbs.twimg.com/media/Ejl0z78XcAMLStH.jpg",
        posterUrl: "https://scontent.fbma6-1.fna.fbcdn.net/v/t39.30808-6/506449592_1373793850568105_681691114474787311_n.jpg?_nc_cat=104&ccb=1-7&_nc_sid=aa7b47&_nc_ohc=eIbqAMfXkPQQ7kNvwHcXgGk&_nc_oc=AdmRutM2dY4GYArzRxn3x5zu3VxzrD7eT1Rh0Nx-gfTXG4Inl1bB5SgMp7kuf31ptd4&_nc_zt=23&_nc_ht=scontent.fbma6-1.fna&_nc_gid=NOFFjaAgXe3AlVdoQ002fw&oh=00_AfqGhjFxLMZsqbZEHwS1CHQ1O_IMUwVAwaq8giL7arWL7Q&oe=6975B53A",
        promo: true,
        nickname: ["Enzo"],
      },
 
      {
        id: "matt-donovan",
        firstName: "Matt",
        lastName: "Donovan",
        imageUrl: "https://preview.redd.it/say-something-nice-about-matt-donovan-v0-c8iu99xfhrmd1.jpeg?auto=webp&s=91149b51cabf9db3aad5910ff02128f3cc32fe57",
        posterUrl: "https://i.ebayimg.com/images/g/wxkAAOSwQUdkoddj/s-l1200.jpg",
        promo: true,
      },
      {
        id: "jenna-sommers",
        firstName: "Jenna",
        lastName: "Sommers",
        imageUrl: "https://i.redd.it/6jrsxwkg2w4c1.jpeg",
        posterUrl: "https://imagez.tmz.com/image/08/4by3/2022/01/28/08465c8a86bd440ab0b215b60e46a79b_xl.jpg",
        promo: true,
      },
      {
        id: "vicki-donovan",
        firstName: "Vicki",
        lastName: "Donovan",
        imageUrl:
          "https://i.pinimg.com/736x/a2/cf/ba/a2cfba76c8f8355849b6941ec60f4bd1.jpg",
        promo: false,
      },
    ],
    cast: [
      { actor: "Nina Dobrev", character: "Elena Gilbert" },
      { actor: "Paul Wesley", character: "Stefan Salvatore" },
      { actor: "Ian Somerhalder", character: "Damon Salvatore" },
      { actor: "Steven R. McQueen", character: "Jeremy Gilbert" },
      { actor: "Sara Canning", character: "Jenna Sommers" },
      { actor: "Kat Graham", character: "Bonnie Bennett" },
      { actor: "Candice King", character: "Caroline Forbes" },
      { actor: "Zach Roerig", character: "Matt Donovan" },
      { actor: "Kayla Ewell", character: "Vicki Donovan" },
      { actor: "Michael Trevino", character: " Tyler Lockwood" },
      { actor: "Matt Davis", character: "Alaric Saltzman" },
      { actor: "Joseph Morgan", character: "Klaus Mikaelson" },
      { actor: "Michael Malarkey", character: "Enzo St. John" },
    ],
    seasons: [
      {
        id: "the-vampire-diaries-season-1",
        seasonNumber: 1,
        premiereDate:  "September 10, 2009" ,
        finaleDate:  "May 13, 2010" ,
        premiereEpisode: "Pilot",
        finaleEpisode: "Founder's Day",
        title: "The Vampire Diaries, Season 1",
        posterUrl:
          "https://assets.mycast.io/posters/the-vampire-diaries-fan-casting-poster-47929-large.jpg?1595364878",
        episodeCount: 22,
      },
      {
        id: "the-vampire-diaries-season-2",
        seasonNumber: 2,
        premiereDate:  "September 19, 2010" ,
        finaleDate:  "May 12, 2011" ,
        premiereEpisode: "The Return",
        finaleEpisode: "As I Lay Dying",
        title: "The Vampire Diaries, Season 2",
        posterUrl:
          "https://irs.www.warnerbros.com/keyart-jpeg/vampire_diaries_season2_keyart.jpg",
        episodeCount: 22,
      },
      {
        id: "the-vampire-diaries-season-3",
        seasonNumber: 3,
        premiereDate:  "September 15, 2011" ,
        finaleDate:  "May 10, 2012" ,
        premiereEpisode: "The Birthday",
        finaleEpisode: "The Departed",
        title: "The Vampire Diaries, Season 3",
        posterUrl:
          "https://i.ebayimg.com/images/g/7rEAAOSwaVBlpoa6/s-l1600.webp",
        episodeCount: 22,
      },
      {
        id: "the-vampire-diaries-season-4",
        seasonNumber: 4,
        premiereDate:  "2012-10-11" ,
        finaleDate:  "May 16, 2013" ,
        premiereEpisode: "Growing Pains",
        finaleEpisode: "Graduation",
        title: "The Vampire Diaries, Season 4",
        posterUrl:
          "https://th.bing.com/th/id/OIP.IWL4RTQpoksGNVFdhjklHgHaLM?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3",
        episodeCount: 22,
      },
      {
        id: "the-vampire-diaries-season-5",
        seasonNumber: 5,
        premiereDate:  "2013-10-03" ,
        finaleDate:  "May 15, 2013" ,
        premiereEpisode: "I Know What You Did Last Summer",
        finaleEpisode: "Home",
        title: "The Vampire Diaries, Season 5",
        posterUrl:
          "https://imusic.b-cdn.net/images/item/original/408/5051892163408.jpg?vampire-diaries-s5-dvds-2014-the-vampire-diaries-season-5-dvd&class=scaled&v=1405954495",
        episodeCount: 22,
      },
      {
        id: "the-vampire-diaries-season-6",
        seasonNumber: 6,
        premiereDate:  "2014-10-02" ,
        finaleDate:  "May 14, 2015" ,
        premiereEpisode: "I'll Remember",
        finaleEpisode: "I'm Thinking of You All the While",
        title: "The Vampire Diaries, Season 6",
        posterUrl:
          "https://i.pinimg.com/736x/4d/aa/ad/4daaadd22b32a65b4ab1d4308523b7ab.jpg",
        episodeCount: 22,
      },
      {
        id: "the-vampire-diaries-season-7",
        seasonNumber: 7,
        premiereDate:  "2015-10-08" ,
        finaleDate:  "May 13, 2016" ,
        premiereEpisode: "Day One of Twenty-Two Thousand, Give or Take",
        finaleEpisode: "Gods and Monsters",
        title: "The Vampire Diaries, Season 7",
        posterUrl:
          "https://i.pinimg.com/736x/3e/67/7e/3e677e4184179912bf4d07b7db8b7054.jpg",
        episodeCount: 22,
      },
      {
        id: "the-vampire-diaries-season-8",
        seasonNumber: 8,
        premiereDate:  "2016-10-21" ,
        finaleDate:  "2017-03-10" ,
        premiereEpisode: "Hello, Brother",
        finaleEpisode: "I Was Feeling Epic",
        title: "The Vampire Diaries, Season 8",
        posterUrl:
          "https://i.pinimg.com/736x/5f/de/49/5fde492015d389cf663a7a7c38b95f52.jpg",
        episodeCount: 16,
      },
    ],
    soundtrack: [
      {
        id: "the-vampire-diaries-season-1-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 1,
      },
      {
        id: "the-vampire-diaries-season-2-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 2,
      },
      {
        id: "the-vampire-diaries-season-3-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 3,
      },
      {
        id: "the-vampire-diaries-season-4-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 4,
      },
      {
        id: "the-vampire-diaries-season-5-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 5,
      },
      {
        id: "the-vampire-diaries-season-6-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 6,
      },
      {
        id: "the-vampire-diaries-season-7-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 7,
      },
      {
        id: "the-vampire-diaries-season-8-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 8,
      },
    ],
    basedOn: true,
    composer: ["Micheal Suby"],
    creator: ["Julie Plec"],
    producer: ["Julie Plec"],
    executive: [
      "Kevin Williamson",
      "Julie Plec",
      "Leslie Morgenstein",
      "Bob Levy",
      "Caroline Dries",
      "Melinda Hsu Taylor",
      "Chad Fiveash",
      "James Stoteraux",
    ],
    prodLocation: [
      "Atlanta, Georgia",
      "Covington, Georgia",
      "Vancouver, British Columbia (pilot)",
    ],
    prodCompanies: [
      "Outerbanks Entertainment",
      "Alloy Entertainment",
      "Bonanza Productions",
      "CBS Television Studios",
      "Warner Bros. Television",
    ],
    network: ["The CW"],
    related: [
      { 
        id: "the-vampire-diaries-book",
        title: "The Vampire Diaries (Book Series)",
        posterUrl: "https://cdn.shopify.com/s/files/1/0338/4872/1545/products/61pi-TJdTUL.jpg?v=1646235983",
      },
      { 
        id: "the-vampire-diaries-a-darker-truth",
        title: "The Vampire Diaries: A Darker Truth",
        posterUrl: "https://media.myshows.me/shows/normal/3/cf/3cf47a65016b392436a23dd290f32a73.jpg",
      },
      { 
        id: "the-originals",
        title: "The Originals",
        posterUrl: "https://m.media-amazon.com/images/M/MV5BNTQzMTExNzU0NV5BMl5BanBnXkFtZTgwMjgzNDIxMDE@._V1_.jpg",
      },
      { 
        id: "the-originals-the-awakening",
        title: "The Originals: The Awakening",
        posterUrl: "https://m.media-amazon.com/images/M/MV5BMTllMmNlZmYtZGJmNS00NGJjLWFkZTgtNjU5OTM4MDk3ZGRjXkEyXkFqcGc@._V1_.jpg",
      },
      { 
        id: "legacies",
        title: "Legacies",
        posterUrl: "https://m.media-amazon.com/images/M/MV5BZmMzYzYwMjItOWRiNi00NmU3LWI2ZjktOWFjYzI5ZmI4ZDI0XkEyXkFqcGc@._V1_.jpg",
      },
    ],
  },
    {
    id: "wednesday",
    title: "Wednesday",
    posterUrl: "https://media.s-bol.com/x56VGoEmY8O9/61MxzV/802x1200.jpg",
    country: "US",
    language: "En",
    firstAirDate: "November 23, 2022",
    lastAirDate: "TBA",
    status: "Airing",
    numberOfSeasons: 2,
    numberOfEpisodes: 16,
    tags: ["drama", "netflix", "academy", "dark-comedy"],
    plot: "Wednesday Addams enrolls at Nevermore Academy and investigates a string of murders while navigating friendships, rivalries, and her own emerging psychic abilities.",
    mainCharacters: [
      {
        id: "wednesday-addams",
        firstName: "Wednesday",
        lastName: "Addams",
        imageUrl: "https://assets.vogue.in/photos/63a539e408387311b87d6abe/2:3/w_2560%2Cc_limit/Wednesday%2520Addams%2520Vogue%2520India.jpg",
        posterUrl: "https://i.pinimg.com/736x/32/52/5c/32525c5a02a623e84041ccd6d998b4d0.jpg",
        promo: true,
      },
      {
        id: "enid-sinclair",
        firstName: "Enid",
        lastName: "Sinclair",
        imageUrl: "https://preview.redd.it/just-finished-binging-through-the-first-season-of-the-show-v0-b6bbjtqspnpf1.jpeg?width=640&crop=smart&auto=webp&s=255832cbd2a8d3f92d6d7eeeee80619a029057ab",
        posterUrl: "https://cdn.polyspeak.ai/speakmaster/64ace6c40b68a9ff7f833124580e8d80.webp",
        promo: true,
      },
      {
        id: "tyler-galpin",
        firstName: "Tyler",
        lastName: "Galpin",
        imageUrl: "https://assets.mycast.io/actor_images/actor-tyler-galpin-wednesday-608847_large.jpg",
        posterUrl:  "https://preview.redd.it/whos-a-worse-person-v0-s665t4wx2rpf1.jpg?width=1080&crop=smart&auto=webp&s=748e76b3bb781ec44ebb6a4a082033525a1e9ad6",
        promo: true,
      },
      {
        id: "xavier-thorpe",
        firstName: "Xavier",
        lastName: "Thorpe",
        imageUrl: "https://i.redd.it/zlw7yhsbdt5b1.jpg",
        posterUrl: "https://www.hindustantimes.com/ht-img/img/2025/08/06/1600x900/fdfddd_1754487194526_1754487207399.jpg",
        promo: true,
      },
      {
        id: "larissa-weems",
        firstName: "Larissa",
        lastName: "Weems",
        imageUrl: "https://preview.redd.it/whats-your-favorite-principal-larissa-weems-quote-the-v0-ipfqiwe5ic6b1.jpg?width=640&crop=smart&auto=webp&s=248a66788704179a3f3360c0fdab247b2baa441e",
        posterUrl: "https://static0.srcdn.com/wordpress/wp-content/uploads/2025/08/mixcollage-14-aug-2025-04-12-pm-6162.jpg?q=70&fit=crop&w=1600&h=900&dpr=1",
        promo: true,
      },
      {
        id: "bianca-barclay",
        firstName: "Bianca",
        lastName: "Barclay",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHBBqLS-MlEgoYXk3dnU5QY6hfTx4Ti5dmP-2HE0QtHXIrP9v9GUH1Kkkz&s=10",
        posterUrl: "https://i.pinimg.com/736x/9c/2a/30/9c2a30f658b1317b01a3a9f0f71409da.jpg",
        promo: true,
      },
      {
        id: "ajax-petropolus",
        firstName: "Ajax",
        lastName: "Petropolus",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQ2MOu0mYolDqRzVUysVUhPU1eQIOpTbp3E30QM_Fd6QXdT9pWB9HZAUsB&s=10",
        posterUrl: "https://i.pinimg.com/736x/fc/97/02/fc9702e95d16953306666da99a0c04cf.jpg",
        promo: true,
      },
      {
        id: "eugene-ottinger",
        firstName: "Eugene",
        lastName: "Ottinger",
        imageUrl: "https://i.pinimg.com/564x/2d/0f/e3/2d0fe3c9140fe0f7a1e898245fe27d54.jpg",
        posterUrl: "https://i.pinimg.com/736x/bc/a7/2b/bca72b5e47174665c7a968e0c237afb0.jpg",
        promo: true,
      },
      {
        id: "marilyn-thornhill",
        firstName: "Marilyn",
        lastName: "Thornhill",
        imageUrl: "https://i.pinimg.com/736x/8d/bb/36/8dbb36653e944db28db5056a76a0e80e.jpg",
        posterUrl: "https://www.vanquishe.com/wp-content/uploads/2024/11/Marilyn-Thornhill-Wednesday-Brown-Jacket.webp",
        promo: true,
      },
      {
        id: "morticia-addams",
        firstName: "Morticia",
        lastName: "Addams",
        imageUrl: "https://static.wikia.nocookie.net/timburton/images/9/91/Profile-Morticia_Addams.png/revision/latest/scale-to-width-down/1200?cb=20250913030526",
        posterUrl: "https://hips.hearstapps.com/hmg-prod/images/wednesday-105-unit-04110rc-1670233231.jpg?crop=0.533xw:1.00xh;0.245xw,0&resize=980:*",
        promo: true,
      },
      {
        id: "gomez-addams",
        firstName: "Gomez",
        lastName: "Addams",
        imageUrl:
          "https://thecelebjackets.com/wp-content/uploads/2025/08/Wednesday-S02-Gomez-Addams-Pinstriped-Blazer-1.png",
        promo: true,
      },
      {
        id: "uncle-fester",
        firstName: "Uncle",
        lastName: "Fester",
        imageUrl: "https://static.wikia.nocookie.net/characters/images/8/85/Fester_Addams_%28Wednesday%29.jpg/revision/latest?cb=20230619033509",
        posterUrl: "https://thecelebjackets.com/wp-content/uploads/2025/08/Wednesday-S02-Uncle-Fester-Light-Single-Breasted-Coat.png",
        promo: true,
      },
    ],
    cast: [
      { actor: "Jenna Ortega", character: "Wednesday Addams", creditOrder: 1 },
      { actor: "Emma Myers", character: "Enid Sinclair", creditOrder: 2 },
      { actor: "Hunter Doohan", character: "Tyler Galpin", creditOrder: 3 },
      {
        actor: "Percy Hynes White",
        character: "Xavier Thorpe",
        creditOrder: 4,
      },
      {
        actor: "Gwendoline Christie",
        character: "Larissa Weems",
        creditOrder: 5,
      },
    ],
    seasons: [
      {
        id: "wednesday-season-1",
        seasonNumber: 1,
        premiereDate:  "2022-11-23" ,
        premiereEpisode: "Wednesday's Child Is Full of Woe",
        finaleEpisode: "A Murder of Woes",
        title: "Wednesday, Season 1",
        posterUrl:
          "https://realwomenofgaming.com/wp-content/uploads/2022/11/wednesday.jpg",
        episodeCount: 8,
      },
      {
        id: "wednesday-season-2",
        seasonNumber: 2,
        premiereDate:  "August 06, 2025" ,
        finaleDate:  "September 03, 2025" ,
        premiereEpisode: "Here We Woe Again",
        finaleEpisode: "This Means Woe",
        title: "Wednesday, Season 2",
        posterUrl:
          "https://static.wikia.nocookie.net/addamsfamily/images/0/0a/Wednesday_Season_2_Poster_001.jpg/revision/latest?cb=20250422205134",
        episodeCount: 8,
      },
    ],
    soundtrack: [
      {
        id: "wednesday-season-1",
        type: "soundtrack",
        noSeason: 1,
        noImage: true,
      },
      {
        id: "wednesday-season-2",
        type: "soundtrack",
        noSeason: 2,
        noImage: true,
      },
    ],
    creator: ["Alfred Gough", "Miles Millar"],
    producer: ["Carmen Pepelea"],
    executive: [
      "Alfred Gough",
      "Miles Millar",
      "Tim Burton",
      "Steve Stark",
      "Andrew Mittman",
      "Gail Berman",
      "Kayla Alpert",
      "Jonathan Glickman",
      "Tommy Harper",
      "Kevin Lafferty",
      "Kevin Miserocchi",
      "Karen Richards",
      "Meredith Averill",
    ],
    prodLocation: ["Bucharest, Romania"],
    prodCompanies: [
      "Millar Gough Ink",
      "Tim Burton Productions",
      "Toluca Pictures",
      "MGM Television",
    ],
    network: ["Netflix"],
    related: [
      {
        id: "the-addams-family",
        posterUrl: "https://m.media-amazon.com/images/M/MV5BZmQyODM1NmEtZDgwZi00ZWU5LWI4MzItOWZjYzRhNjkwZTg3XkEyXkFqcGc@._V1_.jpg"
      }
    ],
  },
  {
    id:"andor", 
    title: "Andor", 
    posterUrl: "https://static.wikia.nocookie.net/starwars/images/6/6e/AndorPosterFull.jpg/revision/latest?cb=20220802224227",
    firstAirDate: "2022", 
    lastAirDate: "2025",
    tags: [
      "Action-adventure",
      "Drama",
      "Dystopia",
      "Political thriller",
      "Spy thriller",
      "Science fiction",
    ],
  },
  {
    id:"loki", 
    title: "Loki", 
    posterUrl: "https://m.media-amazon.com/images/M/MV5BYzA2YjM2ZWQtYTZhMS00OTI3LTlhYzQtZjBiZWZkMDdlNjA5XkEyXkFqcGc@._V1_.jpg",
    firstAirDate:"2021", 
    lastAirDate: "2023",
    tags: [ 	
      "Action-adventure",
      "Crime thriller",
      "Fantasy",
      "Procedural drama",
      "Science fiction",
      "Superhero",
    ]
  },
   {
    id:"gotham", 
    title: "Gotham", 
    posterUrl: "https://static.wikia.nocookie.net/marvel_dc/images/b/bc/Gotham_TV_Series_002.jpg/revision/latest?cb=20241117144251",
    firstAirDate: "2014",
    lastAirDate: "2019",
    tags: [
      "Crime drama",
      "Action",
      "Superhero",
    ]
    
   },
    {
    id: "buffy-the-vampire-slayer",
    title: "Buffy the Vampire Slayer",
    plot: "A high school student discovers she is the Chosen One, destined to fight vampires and demons. Balancing school, friendships, and saving the world becomes her everyday reality.",
    tags: ["Supernatural", "Teen drama", "Horror", "Comedy-drama"],
    firstAirDate: "March 10, 1997",
    lastAirDate: "May 20, 2003",
    status: "Ended",
    language: "en",
    country: "USA",
    posterUrl:
      "https://m.media-amazon.com/images/M/MV5BMDk4MGVkNDAtZjQwZi00MDc3LWE4MmEtY2YyODQ2NDQyMjgxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    numberOfSeasons: 7,
    numberOfEpisodes: 144,
    mainCharacters: [
      {
        id: "buffy-summers",
        firstName: "Buffy",
        lastName: "Summers",
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/a/a2/S514_Buffy.png?utm_source=en.wikipedia.org&utm_campaign=index&utm_content=original",
        posterUrl:  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWpnhodBoSHKqJzKto6MiAxKEOHv-HAjSz8jGrr-AUuZtRwOuf",
        promo: true,
      },
      {
        id: "xander-harris",
        firstName: "Xander",
        lastName: "Harris",
        imageUrl: "https://cdn.mos.cms.futurecdn.net/aveDNKPg7FbVWth6XwngdK.png",
        posterUrl:  "https://m.media-amazon.com/images/M/MV5BMTM3NTA3MzM3N15BMl5BanBnXkFtZTYwMTY4NjEz._V1_.jpg",
        promo: true,
      },
      {
        id: "willow-rosenberg",
        firstName: "Willow",
        lastName: "Rosenberg",
        imageUrl: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhkDNvjXjrcM4F4YUpFM83fJqPaqUQKvKI0gkZs9Tyy6F1hzqhfxhwBhd8TaPPlw7p6UTKEboQgiGlS07lZf_Gz9gkBqRn_YJGE_5drga9U-6xkRXusN8VdZ2h_4ssc0CHPh1oFi5JjC-8Y/s1600/WillowFeatured.jpg",
        posterUrl:  "https://ucarecdn.com/2df32aec-57cb-427d-b66c-f81cb957663f/-/crop/320x320/60,0/-/preview/-/progressive/yes/-/format/auto/",
        promo: true,
      },
      {
        id: "cordelia-chase",
        firstName: "Cordelia",
        lastName: "Chase",
        imageUrl: "https://static0.srcdn.com/wordpress/wp-content/uploads/2025/06/charisma-carpenter-as-cordelia-chase-smiling-widely-in-buffy-the-vampire-slayer.jpg?w=1600&h=900&fit=crop",
        posterUrl:  "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRicE25m61JCW8sweAUIYkbEyXTL_sUzZtbkFMGquMqlQ9Rz67k",
        promo: true,
      },
      {
        id: "angel",
        firstName: "Liam",
        imageUrl: "https://static0.srcdn.com/wordpress/wp-content/uploads/David-Boreanz-as-Angel-in-Buffy-the-Vampire-Slayer.jpg",
        posterUrl:  "https://static0.srcdn.com/wordpress/wp-content/uploads/2021/03/David-Boreanaz-as-Angel-in-BtVS-Angel.jpg?q=49&fit=contain&w=711&h=400&dpr=2",
        promo: true,
        nickname: ["Angel"],
        goesByNickname: true,
      },
      {
        id: "oz",
        firstName: "Daniel",
        lastName: "Osbourne",
        imageUrl: "https://i.redd.it/i-adore-oz-v0-3dy1acifkxsb1.jpg?width=1080&format=pjpg&auto=webp&s=52273151ab399c870292368ee5f3272c73a1b7e1",
        posterUrl:  "https://static0.srcdn.com/wordpress/wp-content/uploads/2020/04/Oz-Buffy-the-Vampire-Slayer-Season-2.jpg",
        promo: true,
        nickname: ["Oz"],
        goesByNickname: true,
      },
      {
        id: "riley-finn",
        firstName: "Riley",
        lastName: "Finn",
        imageUrl: "https://preview.redd.it/was-riley-really-that-terrible-v0-xt412s4bbmve1.png?width=640&crop=smart&auto=webp&s=d8d888c892b032a92cb04baa90f87012a86dcb0b",
        posterUrl: "https://i.redd.it/h33g206yph5e1.png",
        promo: true,
      },
      {
        id: "anya-jenkins",
        firstName: "Anya",
        lastName: "Jenkins",
        imageUrl: "https://preview.redd.it/anya-jenkins-v0-mkxrqwdefekg1.jpg?width=600&format=pjpg&auto=webp&s=2a21516608a32005bdb4450db8a4271e6a2cafcf",
        posterUrl:  "https://preview.redd.it/what-do-my-favorite-characters-say-about-me-v0-emm3rzulbitc1.jpg?width=225&format=pjpg&auto=webp&s=b190aa4ca090e0edad637d36ea1d61eaa8f536e3",
        promo: true,
      },
      {
        id: "dawn-summers",
        firstName: "Dawn",
        lastName: "Summers",
        imageUrl: "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2023/10/buffy-the-vampire-slayer-dawn.jpg",
        posterUrl: "https://yellowroseroad.wordpress.com/wp-content/uploads/2021/05/dawnsummers.png",
        promo: true,
      },
      {
        id: "tara-maclay",
        firstName: "Tara",
        lastName: "Maclay ",
        imageUrl: "https://miro.medium.com/1*6Ipj73CHBi9wmvuoNd0JJg.png",
        posterUrl:  "https://oyster.ignimgs.com/mediawiki/apis.ign.com/buffy-the-vampire-slayer/1/13/Taramaclay.jpg",
        promo: true,
      },
      {
        id: "spike",
        firstName: "William",
        lastName: "Pratt",
        imageUrl: "https://a1cf74336522e87f135f-2f21ace9a6cf0052456644b80fa06d4f.ssl.cf2.rackcdn.com/images/characters/large/800/Spike.Buffy-the-Vampire-Slayer.webp",
        posterUrl: "https://oyster.ignimgs.com/mediawiki/apis.ign.com/buffy-the-vampire-slayer/7/7c/Spike.jpg",
        promo: true,
        nickname: ["Spike"],
        goesByNickname: true,
      },
      {
        id: "rupert-giles",
        firstName: "Rupert",
        lastName: "Giles",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BNTk3YmY2M2QtYTkxZC00NWNlLWEyYWYtYWExYzdlMDRjMTE2XkEyXkFqcGc@._V1_.jpg",
        posterUrl:  "https://oyster.ignimgs.com/mediawiki/apis.ign.com/buffy-the-vampire-slayer/d/da/Rupertgiles.jpg",
        promo: true,
      },
    ],
    cast: [
      { actor: "Sarah Michelle Gellar", character: "Buffy Summers" },
      { actor: "Nichol Brendons", character: "Xander Harris" },
      { actor: "Alyson Hannigan", character: "Willow Rosenberg" },
      { actor: "Charisma Carpenter", character: "Cordelia Che" },
      { actor: "David Boreanaz", character: "Angel" },
      { actor: "Seth Green", character: "Oz" },
      { actor: "Marc Bluc", character: "Riley Finn" },
      { actor: "Emma Caulfield", character: "Anya Jenkins" },
      { actor: "Michelle Trachtenberg", character: "Dawn Summers" },
      { actor: "Amber Benson", character: "Tara Maclay " },
      { actor: "James March ters", character: "Spike" },
      { actor: "Anthony Stewart Head", character: "Rupert Giles" },
    ],
    seasons: [
      {
        id: "buffy-the-vampire-slayer-season-1",
        seasonNumber: 1,
        premiereDate:  "1997-03-10" ,
        finaleDate:  "1997-06-02" ,
        premiereEpisode: "Welcome to the Hellmouth",
        finaleEpisode: "Prophecy Girl",
        title: "Buffy the Vampire Slayer, Season 1",
        posterUrl:
          "https://i.pinimg.com/736x/2e/52/87/2e5287f1e49bcc080166493575950d30.jpg",
        episodeCount: 12,
      },
      {
        id: "buffy-the-vampire-slayer-season-2",
        seasonNumber: 2,
        premiereDate:  "September 15, 1997" ,
        finaleDate:  "May 19, 1998" ,
        premiereEpisode: "When She Was Bad",
        finaleEpisode: "Becoming (Part 2)",
        title: "Buffy the Vampire Slayer, Season 2",
        posterUrl:
          "https://preview.redd.it/i-cant-help-but-feel-like-this-season-is-why-twilight-exists-v0-445mkw3plwzd1.jpeg?width=1080&crop=smart&auto=webp&s=ea9cc04cfa461c53735917e9aeb971bac2a5f811",
        episodeCount: 22,
      },
      {
        id: "buffy-the-vampire-slayer-season-3",
        seasonNumber: 3,
        premiereDate:  "September 20, 1998" ,
        finaleDate:  "July 13, 1999" ,
        premiereEpisode: "Anne",
        finaleEpisode: "Graduation Day (Part 2)",
        title: "Buffy the Vampire Slayer, Season 3",
        posterUrl:
          "https://i.pinimg.com/736x/b1/e0/83/b1e083d2dc7ce032d53e0d39ddd7ace8.jpg",
        episodeCount: 22,
      },
      {
        id: "buffy-the-vampire-slayer-season-4",
        seasonNumber: 4,
        premiereDate:  "1999-10-05" ,
        finaleDate:  "May 23, 2000" ,
        premiereEpisode: "The Freshman",
        finaleEpisode: "Restless",
        title: "Buffy the Vampire Slayer, Season 4",
        posterUrl:
          "https://media.themoviedb.org/t/p/w440_and_h660_face/mwLPMMazdcnsMJ4dfEZFw3SjK7q.jpg",
        episodeCount: 22,
      },
      {
        id: "buffy-the-vampire-slayer-season-5",
        seasonNumber: 5,
        premiereDate:  "September 26, 2000" ,
        finaleDate:  "May 22, 2001" ,
        premiereEpisode: "Buffy vs. Dracula",
        finaleEpisode: "The Gift",
        title: "Buffy the Vampire Slayer, Season 5",
        posterUrl:
          "https://media.themoviedb.org/t/p/w440_and_h660_face/kGpDRY64TgOYUh4YGcj574Ckvop.jpg",
        episodeCount: 22,
      },
      {
        id: "buffy-the-vampire-slayer-season-6",
        seasonNumber: 6,
        premiereDate:  "2001-10-02" ,
        finaleDate:  "May 21, 2002" ,
        premiereEpisode: "Bargaining (Part 1)",
        finaleEpisode: "Grave",
        title: "Buffy the Vampire Slayer, Season 6",
        posterUrl:
          "https://media.themoviedb.org/t/p/w440_and_h660_face/aAJLnT7nSD5JaZcyUElyp4dYpmq.jpg",
        episodeCount: 22,
      },
      {
        id: "buffy-the-vampire-slayer-season-7",
        seasonNumber: 7,
        premiereDate:  "September 24, 2002" ,
        finaleDate:  "May 20, 2003" ,
        premiereEpisode: "Lessons",
        finaleEpisode: "Chosen",
        title: "Buffy the Vampire Slayer, Season 7",
        posterUrl:
          "https://media.themoviedb.org/t/p/w440_and_h660_face/lkJ4GivhY2IJRIeLPw8zavHNfCv.jpg",
        episodeCount: 22,
      },
    ],
    soundtrack: [
      {
        id: "buffy-the-vampire-slayer-season-1-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 1,
      },
      {
        id: "buffy-the-vampire-slayer-season-2-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 2,
      },
      {
        id: "buffy-the-vampire-slayer-season-3-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 3,
      },
      {
        id: "buffy-the-vampire-slayer-season-4-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 4,
      },
      {
        id: "buffy-the-vampire-slayer-season-5-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 5,
      },
      {
        id: "buffy-the-vampire-slayer-season-6-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 6,
      },
      {
        id: "buffy-the-vampire-slayer-season-7-soundtrack",
        type: "soundtrack",
        noImage: true,
        noSeason: 7,
      },
    ],
    creator: ["Joss Whedon"],
    producer: ["Joss Whedon"],
    executive: [
      "Joss Whedon",
      "David Greenwalt",
      "Marti Noxon",
      "David Fury",
      "Fran Rubel Kuzui",
      "Kaz Kuzui",
    ],
    prodLocation: ["Los Angeles, California"],
    prodCompanies: [
      "Mutant Enemy Productions",
      "Sandollar Television",
      "Kuzui Enterprises",
      "20th Century Fox Television",
    ],
    network: ["The WB", "UPN"],
    related: [
      {
        id: "buffy-the-vampire-slayer-film", 
        title: "Buffy the Vampire Slayer (Film)",
        posterUrl: "https://m.media-amazon.com/images/M/MV5BZDQ4MzNlMzAtZDMxMy00YzcwLWJiMTMtNDBmMWMyMTAwODM5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg"
      },
      {
        id: "buffy-the-vampire-slayer-season-eight-comic-book", 
        title: "Buffy the Vampire Slayer: Season Eight (Comic Book)",
        posterUrl: "https://m.media-amazon.com/images/I/61D+duAzolL._AC_UF1000,1000_QL80_.jpg"
      },
      {
        id: "angel", 
        title: "Angel",
        posterUrl: "https://m.media-amazon.com/images/M/MV5BMjQzMTliMWYtNDQ3Ny00MTdmLWJjODQtNTk3NTcyZDMwMmMwXkEyXkFqcGc@._V1_.jpg"
      },
      {
        id: "buffy-the-vampire-slayer-new-sunnydale ", 
        title: "Buffy the Vampire Slayer: New Sunnydale",
        posterUrl: "https://m.media-amazon.com/images/M/MV5BNTU3OWE1NDQtYWY5YS00ZWFhLWFkODQtYzg2ZWY5OGE1MzFlXkEyXkFqcGc@._V1_.jpg"
      },
    ],
  },

  {
    id:"the-witcher", 
    title: "The Witcher", 
    firstAirDate: "2019"
 },
  {
    id:"spider-noir", 
    title: "Spider-Noir", 
    firstAirDate: "2026"
  },
  {
    id:"it-welcome-to-derry",
    title:  "IT: Welcome to Derry", 
    firstAirDate: "2025"
 },
  {
    id:"3-body-problem", 
    title: "3 Body Problem", 
    firstAirDate: "2024"
  },
  {
    id:"true-blood",
    title: "True Blood", 
    firstAirDate: "2008", 
    lastAirDate: "2014"
  },
  {
    id:"the-mandalorian",
    title: "The Mandalorian", 
    firstAirDate: "2019", 
    lastAirDate: "2023"
  },
  {
    id:"the-boroughs", 
    title: "The Boroughs", 
    firstAirDate: "2026"
  },
  {
    id:"ghosts", 
    title: "Ghosts", 
    firstAirDate: "2021"
  },
  {
    id:"the-leftovers",
    title: "The Leftovers",
    firstAirDate: "2014", 
    lastAirDate: "2017"
  },
  {
    id:"daredevil-born-again",
    title:  "Daredevil: Born Again", 
    firstAirDate: "2025",
  },
  {
    id:"bleach", 
    title: "Bleach", 
    firstAirDate: "2004", 
    lastAirDate: "2012"
  },
  {
    id:"death-note", 
    title: "Death Note", 
    firstAirDate: "2006", 
    lastAirDate: "2007"},
  {
    id:"lucifer",
    title: "Lucifer", 
    firstAirDate: "2016", 
    lastAirDate: "2021"
  },
  {
    id:"arcane", 
    title: "Arcane", 
    firstAirDate: "2021", 
    lastAirDate: "2024"
  },
  {
    id:"one-piece-live-action", 
    lastAirDate: "One Piece", 
    firstAirDate: "2023",
  },
  {
    id:"hunter-x-hunter", 
    title: "Hunter X Hunter",
    firstAirDate: "2011", 
    lastAirDate: "2014"
  },
  {
    id:"stranger-things-tales-from-85", 
    title: "Stranger Things: Tales from '85", 
    firstAirDate: "2026"
  },
  {
    id:"fullmetal-alchemist-brotherhood", 
    title: "Fullmetal Alchemist: Brotherhood", 
    firstAirDate: "2009", 
    lastAirDate: "2010"
  },
  {
    id:"talamasca-the-secret-order", 
    title: "Talamasca: The Secret Order", 
    firstAirDate: "2025", 
    lastAirDate: "2026"
  },
  {
    id:"avatar-the-last-airbender", 
    title: "Avatar: The Last Airbender", 
    firstAirDate: "2024",
 },
  {
    id:"demon-slayer", 
    title: "Demon Slayer: Kimetsu no Yaiba", 
    firstAirDate:"2019", 
    lastAirDate: "2024",
  },
  {
    id:"the-good-place",
    title: "The Good Place",
    firstAirDate: "2016", 
    lastAirDate: "2020"
  },
  {
    id:"the-twilight-zone",
    title: "The Twilight Zone",
    firstAirDate: "1959", 
    lastAirDate: "1964"
  },
];
