import { Show } from "../types/Show";

export const kidsSeries: Show[] = [
    {
        id: "soy-luna", 
        title: "Soy Luna",
        posterUrl: "https://cdn.europosters.eu/image/1300/33470.jpg",
        country: "Argentina",
        firstAirDate: "March 14, 2016",
        lastAirDate: "August 17, 2018",
        status: "ended",
        language: "Spanish",
        plot: "Luna Valente lives with her family in Cancún, Mexico. She goes to school, has her own group of friends, has a job, and loves to skate. However, her life changes when her parents are given a job offer that moves them to Buenos Aires, Argentina. There she finds a skating rink named Jam and Roller where she learns free styling. She makes new friends and falls in love with Matteo Balsano.",
        mainCharacters: [
            {
                id: "luna-valente", 
                label: "Luna",
                firstName: "Luna",
                lastName: "Valente", 
                imageUrl: "https://pbs.twimg.com/media/FMki-HEVQAAlv7P.jpg",  
                actor: "Karol Sevilla", 
                personality: "Luna is a sweet, cheerful and big-hearted girl from Mexico. She is optimistic, loyal to her friends and family, and incredibly determined: once she sets herself a goal, she works hard until she reaches it.",    
                promo: true,
            },
            {
                id: "matteo-balsano", 
                label: "Matteo",
                firstName: "Matteo",
                lastEpisode: "Balsano", 
                imageUrl: "https://i.pinimg.com/736x/6a/aa/f1/6aaaf1adbf0e841fa0257a352db1d031.jpg", 
                actor: "Ruggero Pasquarelli", 
                personality: "Matteo starts out as a very presumptuous, vain and seemingly superficial boy, proud of being the 'King of the Track'. Behind the arrogance, he is intelligent, passionate about skating and music, and he gradually shows a genuinely caring and protective side, especially with Luna.",
                promo: true
            },
            {
                id: "simon-alvarez", 
                label: "Simón",
                firstName: "Simón", 
                lastName: "Álvarez",
                imageUrl:  "https://pbs.twimg.com/profile_images/782192147793674244/I0H9Ia9N_400x400.jpg", 
                actor: "Micheal Ronda",
                personality: "Simón is funny, warm and deeply caring. He loves music and skating, is humble and encouraging, and is always ready to support his friends. He often puts other people’s happiness before his own, especially when it comes to Luna.",
                promo: true
            },
            {
              id: "ambar-smith", 
              label: "Ámbar", 
              firstName: "Ámbar",
              lastName: "Smith",
              imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiBer14JbcZC1cqz0-Cn7gzYUcNttoBotJ0y4eVub1a6HcSRgaGxzg1wE&s=10", 
              actor: "Valentina Zenere", 
              personality: "Ámbar is initially superficial, spoiled and very competitive. She craves attention, wants to be the best at everything and uses manipulation to get what she wants. Underneath her schemes she is insecure and jealous, especially of Luna’s loving family, and over time her more vulnerable and conflicted side appears.",
              promo: true
            },
            {
              id: "nina-simonetti", 
              label: "Nina", 
              firstName: "Nina",
              lastName: "Simonetti",
              imageUrl: "https://i.pinimg.com/564x/88/72/a2/8872a20dd293eb403e2efb6206e90566.jpg", 
              actor: "Carolina Kopelioff", 
              personality: "Nina is highly intelligent, curious and a bit of a bookworm. She is shy, introverted and insecure at first, often hiding behind her anonymous online persona, but she is also kind, thoughtful and idealistic, slowly learning to believe in herself.",
              promo: true
            },
            {
              id: "delfi-alzamendi", 
              label: "Delfi", 
              firstName: "Delfina",
              lastName: "Alzamendi",
              imageUrl: "https://i.pinimg.com/474x/c3/2f/e4/c32fe4f983dfa2a8f2c5707ec8358de2.jpg", 
              actor: "Malena Ratner",
              personality: "Delfi starts out as a vain, judgmental and gossip-loving girl who follows Ámbar’s lead and cares a lot about image and social media. Underneath she is sensitive, loyal and capable of real kindness, and as she grows, she becomes more independent, empathetic and emotionally mature.", 
              nickname: ["Delfi"],
              promo: true
            },
            {
              id: "gaston-battan", 
              label: "Gastón", 
              firstName: "Gastón",
              lastName: "Battán",
              imageUrl:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2PcUNF_rVxlnWihDPFgSdI1lDr6k5JkPhy1OzXvePu5kObfJz8Kyr-SY&s=10", 
              actor: "Agustìn Bernasconi", 
              personality: "Gastón is popular, charming and confident, but also respectful, rational and more grounded than Matteo. He loves music and books, especially science fiction, and often acts as the voice of reason, even while struggling with his own feelings and expectations.", 
              promo: true
            },
            {
              id: "jazmin-carvajal", 
              label: "Jazmín", 
              firstName: "Jazmín",
              lastName: "Carvajal",
              imageUrl:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMC2ffTEGTHUd_PG_VR6kuo89IQR1lvI63eiA8Tn7u1QJMxlfcUK7u-Pk&s=10", 
              actor: "Katja Martínez", 
              personality:"Jazmín is energetic, dramatic and very talkative, with absolutely no filter. She is obsessed with trends and online fame, often naïve and clueless about what is really going on around her, but she is also affectionate, loyal and capable of real growth when she learns to think for herself.",
              promo: true
            },
            {
              id: "jim-medina", 
              label: "Jim",
              firstName: "Jimena",
              lastName: "Medina", 
              imageUrl: "https://i.pinimg.com/564x/d1/fb/f9/d1fbf97052e502657c3d99a9c4f854f7.jpg", 
              actor: "Ana Jara" , 
              personality: "Jim is creative, impulsive and full of ideas. She is sweet, friendly and very expressive, with a huge passion for dance and choreography. Together with Yam she is bold and adventurous, even if her impulsiveness sometimes gets her into trouble.",
              promo: true
            },
            {
              id: "yam-sanchez", 
              label: "Yam", 
              firstName: "Yamila",
              lastName: "F. Sánchez",
              imageUrl: "https://i.pinimg.com/474x/99/20/4a/99204a7ddc1e80b9289d460df7046a14.jpg", 
              actor: "Chiara Parravicini", 
              personality: "Yam is emotional, romantic and very passionate about music and fashion. She can be insecure and jealous, but she is loyal, hard-working and caring with the people she loves, especially Jim and Ramiro. She grows a lot in self-confidence over the series.",
              promo: true
            },
            {
              id: "ramiro-ponce",
              firstName: "Ramiro",
              lastEpisode: "Ponce", 
              imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjUIZ2hYuSBkVMxmSRHNKOx4WkG1cXGJek5g&s", 
              actor: "Jorge López", 
              personality: "Ramiro is proud, ambitious and easily frustrated when things don’t go his way. He can come across as arrogant and selfish, but behind that he is disciplined and passionate about dance and skating, and he gradually learns to accept his mistakes and show his softer side.",
              promo: true
            },
            {
              id: "pedro-arias",
              firstName: "Pedro",
              lastName: "Arias",
              imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCqrIy9b8aM3nrOH9OMPTqGPMoNnK_qQdLyDhTR01Ob8m9KBQVhAgrUkw&s=10", 
              actor:"Gastón Vietto", 
              personality: "Pedro is good-natured, loyal and slightly awkward, with a big heart. He works hard, loves music and drumming, and is deeply supportive of his friends. He often downplays his own feelings, especially when it comes to love, in order to not hurt anyone.",
              promo: true
            },
            {
              id: "nico-navarro",
              label: "Nico", 
              firstName: "Nicolás",
              lastName: "Navarro",
              imageUrl: "https://pbs.twimg.com/media/CcAai_hWoAEkDs1.jpg", 
              actor: "Lionel Ferro", 
              personality: "Nico is warm, friendly and easy-going, the kind of guy people feel comfortable with right away. He is supportive, fun and a bit goofy, dreams about making music with Pedro, and often acts as a calm, positive presence in the group.",
              promo: true
            },
            {
              id: "tamara-rios",
              firstName: "Tamara",
              lastName: "Ríos", 
              imageUrl: "https://i.ytimg.com/vi/qIa1PHwfBhQ/maxresdefault.jpg", 
              actor: "Luz Capriota", 
              personality: "Tamara is responsible, strict and highly organized, but also fair and caring. As the manager of Jam & Roller she demands discipline and professionalism, yet she genuinely believes in the kids’ talent and acts like a mentor and protective older sister.", 
              promo: true,
            },
            {
              id: "sharon-benson",
              label: "Mrs. Benson",
              firstName: "Sharon",
              lastName: "Benson", 
              imageUrl: "https://pbs.twimg.com/profile_images/896031069849497601/mFX48SWF_400x400.jpg",  
              actor:"Lucila Gandolfo", 
              personality: "Sharon is elegant, cold and calculating. She is a sophisticated businesswoman who is obsessed with control and appearances, willing to lie and manipulate to protect her fortune and her version of the past. Her cruelty often hides deep guilt, fear and denial.",
              promo: true
            },
            {
              id: "rey",
              label: "Rey",
              firstName: "Reinaldo", 
              imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeTnM8jeVkNkCO0yXhd6dwZYQ1O-fZYq8Idg&s", 
              actor: "Rodrigo Pedreira", 
              personality: "Rey is serious, meticulous and extremely loyal to Sharon. He usually shows a stiff, formal and almost emotionless exterior, but he is also anxious and conflicted when their schemes go too far. Over time, his conscience starts to clash with his loyalty.",
              promo: true
            },
            {
              id: "miguel-valente",
              firstName: "Miguel", 
              lastName: "Valente",
              imageUrl: "https://tiermaker.com/images/chart/chart/soy-luna-characters-520944/migueljpg.png", 
              actor: "David Muri", 
              personality: "Miguel is kind, honest and hard-working. He is a devoted father and husband, protective of Luna and always trying to do what is best for his family, even when that means making sacrifices or enduring Sharon’s authority.",
              promo: true
            },
            {
              id: "monica-valente",
              firstName: "Mónica", 
              lastName: "Valente",
              imageUrl: "https://assets.puzzlefactory.com/puzzle/352/239/original.jpg", 
              actor: "Ana Carolina Valsagna", 
              personality: "Mónica is warm, maternal and supportive. She worries a lot and is often emotional, but she is brave when it comes to defending Luna. She acts as an anchor and emotional support for both Luna and Miguel.",
              promo: true
            },
            {
              id: "tino-alcaraz",
              label: "Tino", 
              firstName: "Martin",
              lastName: "Alcaraz",
              imageUrl: "https://i.ytimg.com/vi/yKWQNxzYAb4/maxresdefault.jpg", 
              actor: "Diego Sassi Alcalá", 
              personality: "Tino is clumsy, goofy and comedic. He is well-meaning but not very bright, often messing things up in a funny way. Despite his silliness, he is loyal and affectionate towards his friends, especially Cato and the Valente family.",
              promo: true
        },
            {
              id: "cato-alcoba",
              label: "Cato", 
              firstName: "Catolino",
              lastName: "Alcoba",
              imageUrl: "https://i.ytimg.com/vi/3NX13Fny2q8/maxresdefault.jpg", 
              actor: "Germán Tripel", 
              personality: "Cato is also a comic character, anxious and a bit neurotic compared to Tino. He worries about rules and getting into trouble, but goes along with schemes anyway. He is kind-hearted and, in his own odd way, very loyal and caring.",
              promo: true,
            },
            {
              id: "amanda-alcoba",
              firstName: "Amanda",
              lastName:  "Alcoba",
              imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSo_VfmxLHXpptU86cN1cWJ_E3QZonZdxQ5APCZqgZaB5t_ku7tHNB00AiW&s=10", 
              actor: "Antonella Querzoli", 
              personality: "Amanda often appears cold, strict and distant, but behind that façade she is deeply caring and protective. She is kind to Luna and the Valente family, takes her work seriously and is always willing to help the people she loves, even if she doesn’t always show her feelings openly.", 
              promo: true
            },
            {
              id: "ricardo-simonetti",
              firstName: "Ricardo", 
              lastName: "Simonetti",
              imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3UB2pHyomDgZqpyZUrAK0DC0JaLaZENqJTAMKlA0kYOCNbnoCAQ-01Tw&s=10", 
              actor: "Ezequiel Rodríquez", 
              personality: "Ricardo is creative, absent-minded and somewhat immature at times, but he has a good heart. As Nina’s father he is loving yet clumsy, often not realizing how his choices affect her. Over time he grows more responsible and emotionally open.",
              promo: true
            },
            {
              id: "ana-valparaiso",
              firstName: "Ana", 
              lastName: "Valparaíso",
              imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdo8WoJ7qgNFa-krOzZX4rHSz839_tSIqUGusrDNCCoSlwnE7eKeDVwQxg&s=10", 
              actor: "Caro Ibarro", 
              personality: "Ana is intelligent, strong-willed and professional. She can seem strict or distant, but she cares deeply about Nina and struggles with guilt over past decisions. She learns to communicate better and to balance work with her role as a mother.",
              promo: true,
            },
            {
              id: "mora-barza",
              firstName: "Mora",
              lastName: "Barza",
              imageUrl:  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBFKSCY4aoMvwJfF-2gRsu-x-fTNa7W4RHHlhMwSE7mNEGzZC_P8AnvSE&s=10", 
              actor: "Paula Kohan", 
              personality: "Mora is stylish, confident and creative, with a strong sense of aesthetics. She is initially self-focused and a bit dramatic, but she is also supportive and protective, especially toward Ana, Nina and the Jam & Roller kids.",
              promo: true
        
            },
            {
              id: "juliana",
              label: "Juliana",
              firstName: "Marisa",
              lastName: "Mint", 
              imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRteeJAFNTZcRv0VR-hY8ldSNeRaVTCCvYkMjcFhY9ttgXnZ_c_UDtVNoc&s=10", 
              actor:"Estela Ribeiro", 
              personality: "Juliana, known as Marisa Mint, is disciplined, demanding and highly perfectionistic. She is tough on her students and hides her emotions behind a strict professional façade, but deep down she is passionate about skating and wants to help them reach their full potential.",
              promo: true
            },
            {
              id: "alfredo-bilder",
              firstName: "Alfredo", 
              lastName: "Bilder",
              imageUrl: "https://i0.wp.com/nicolasisasi.com/wp-content/uploads/2023/11/roberto_carnaghi-isasi-web-1.jpg?ssl=1", 
              actor:"Roberto Carnaghi", 
              personality: "Alfredo is gentle, wise and somewhat melancholic. As the elder of the family he regrets past mistakes and wants to repair the damage done. He is affectionate with Luna and tries to guide others toward truth and reconciliation.",
                promo: true
            },
            {
              id: "gary-lopez",
              firstName: "Gary", 
              lastName: "Lopez",
              imageUrl: "https://vignette.wikia.nocookie.net/soyluna/images/b/bd/Gary.jpg/revision/latest?cb=20200625095218", 
              actor: "Joaquín Berthold", 
              personality: "Gary is ambitious, controlling and opportunistic. He focuses on profit and image more than on people’s feelings, and he has no problem using pressure or manipulation to get what he wants from the skaters and the rink.",
              promo: true
            },
            {
              id: "benicio",
              firstName: "Benicio", 
              imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMvE4a-6JLHaZ1DvF2uKuPiS6uWuu5gMs7HyQ_Xrw5T2GUGrAMHVRWMNU&s=10", 
              actor: "Pasquale Di Nuzzo", 
              personality: "Benicio is arrogant, competitive and manipulative. He enjoys provoking others and uses his charm in a self-serving way. Even so, his jealousy and insecurity are often what push him into schemes and bad decisions.",
              promo: true
            },
            {
              id: "emilia",
              firstName: "Emilia", 
              imageUrl: "https://i.pinimg.com/736x/a6/ea/20/a6ea2069ff3aef1a27e5f6c098d7ba97.jpg", 
              actor: "Giovanna Reynaud", 
              personality:     "Emilia is confident, ambitious and highly competitive. She often comes across as arrogant and sharp-tongued, especially when she feels her spotlight is threatened. Behind her tough and glamorous exterior, she is deeply insecure and vulnerable, craving recognition and genuine affection. Over time she reveals a more sensitive and loyal side, especially in her relationship with Benicio and when she finally allows herself to be honest about her feelings.",
              promo: true
            },
            {
              id: "eric-andrande",
              firstName: "Eric", 
              lastName: "Andrande",
              imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNLFUkBgu3XYv3K2nlzIafHSlw76-eoFQZ1AOqdFo6TQXkilnF848NGIMM&s=10", 
              actor: "Jandino", 
              personality:"Eric is kind, a bit shy and slightly awkward, especially when it comes to his crush on Nina. He genuinely wants to help and do a good job at the rink, but often finds himself overwhelmed by Gary’s pressure and the complicated dynamics around him rather than creating drama himself.",
              promo: true
            },
            {
              id: "maggie-garcia",
              label: "Maggie",
              firstName: "Margarita",
              lastName: "García", 
              imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRitLGbjcYLFLEPC3W2dUF_AUMIFrXS13c0jg&s", 
              actor: "Victoria Suárez Battán", 
              personality: "Maggie starts as a sneaky, ambitious spy for Sharon and Rey, using her charm to get information. Underneath, she is insecure and longs for genuine affection. Her relationship with Rey brings out both her manipulative and her vulnerable sides.",
              promo: true
            }
        ],
        cast: [
          {
              character: "Luna Valente", 
              actor: "Karol Sevilla", 
          },
          {
              character: "Matteo Balsano", 
              actor: "Ruggero Pasquarelli", 
            },
          {
              character: "Simón Álvarez",
              imageUrl:  "https://pbs.twimg.com/profile_images/782192147793674244/I0H9Ia9N_400x400.jpg", 
              actor: "Micheal Ronda",
              },
          {
            character: "Ámbar Smith",
            actor: "Valentina Zenere", 
          },
          {
            character: "Nina Simonetti",
            actor: "Carolina Kopelioff", 
          },
          {
            character: "Delfi Alzamendi",
            actor: "Malena Ratner",
          },
          {
            character: "Gastón Battán",
            actor: "Agustìn Bernasconi", 
          },
          {
            character: "Jazmín Carvajal",
            actor: "Katja Martínez", 
            },
          {
            character: "Jim Medina", 
            actor: "Ana Jara" , 
            },
          {
            character: "Yam F. Sánchez",
            actor: "Chiara Parravicini", 
          },
          {
            character: "Ramiro Ponce", 
            actor: "Jorge López", 
          },
          {
            character: "Pedro Arias",
            actor:"Gastón Vietto", 
          },
          {
            character : "Nico Navarro",
            actor: "Lionel Ferro", 
          },
          {
            character: "Tamara Ríos", 
            actor: "Luz Capriota", 
          },
          {
            character: "Sharon Benson", 
            actor:"Lucila Gandolfo", 
          },
          {
            character: "Rey",
            actor: "Rodrigo Pedreira", 
          },
          {
            character: "Miguel Valente",
            actor: "David Muri", 
          },
          {
            character: "Mónica Valente",
            actor: "Ana Carolina Valsagna", 
          },
          {
            character: "Tino Alcaraz",
            actor: "Diego Sassi Alcalá", 
          },
          {
            character: "Cato Alcoba",
            actor: "Germán Tripel", 
          },
          {
            character: "Amanda Alcoba",
            actor: "Antonella Querzoli", 
          },
          {
            character: "Ricardo Simonetti",
            actor: "Ezequiel Rodríquez", 
          },
          {
            character: "Ana Valparaíso",
            actor: "Caro Ibarro", 
          },
          {
            character: "Mora Barza",
            actor: "Paula Kohan", 
          },
          {
            character: "Juliana", 
            actor:"Estela Ribeiro", 
          },
          {
            character: "Alfredo Bilder",
            actor:"Roberto Carnaghi", 
          },
          {
            character: "Gary Lopez",
            actor: "Joaquín Berthold", 
          },
          {
            character: "Benicio", 
            actor: "Pasquale Di Nuzzo", 
          },
          {
            character: "Emilia", 
            actor: "Giovanna Reynaud", 
          },
          {
            character: "Eric Andrande",
            actor: "Jandino", 
          },
          {
            character: "Maggie García", 
            actor: "Victoria Suárez Battán", 
          }
      ],
        seasons: [ 
          { 
            id: "soy-luna-season-1",
            seasonNumber: 1,
            episodeCount: 80,
            premiereDate: "March 14, 2016",
            finaleDate: "August 26, 2016",
            premiereEpisode: "Un sueño, sobre ruedas",
            finaleEpisode: "La final de la InterContinental, sobre ruedas",
            posterUrl: "https://fr.web.img5.acsta.net/pictures/19/09/29/10/35/5133862.jpg",
            title: "Soy Luna: Season 1",
          },
          { 
            id: "soy-luna-season-2",
            seasonNumber: 2,
            episodeCount: 80,
            premiereDate: "April 17, 2017",
            finaleDate: "September 29, 2017",
            premiereEpisode: "¿Un sueño o una pesadilla?, sobre ruedas",
            finaleEpisode: "La final de la Rodafest en México, sobre ruedas",
            posterUrl: "https://image.tmdb.org/t/p/original/78CUmir4MDINMKdkUt4TmW5d7k4.jpg",
            title: "Soy Luna: Season 2",
           }, 
          { 
            id: "soy-luna-season-3",
            seasonNumber: 3,
            episodeCount: 60,
            premiereDate: "April 16, 2018",
            finaleDate: "August 17, 2018",
            premiereEpisode: "El regreso, sobre ruedas",
            finaleEpisode: "Patinamos por una última vez",
            posterUrl: "https://media.themoviedb.org/t/p/w500/4lqWMdbwFmqd8IRpJdn9L2eXY6W.jpg",
            title: "Soy Luna: Season 3",
          
          },
          
        ],
        numberOfSeasons: 3,
        numberOfEpisodes: 220,
        tags: ["Teen", "Drama", "Romance", "Music", "Telenovela"],
        network: ["Disney Channel Latin America"],
        related: ["Violetta", "Bia", "Soy Luna: Volver a rodar"]
    },
    {
        id: "bia", 
        title: "Bia",
        posterUrl: "https://m.media-amazon.com/images/M/MV5BNmM3NDY2MzItZGFiYi00NzAxLThjODctMDgzZTE5YTIxY2NjXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        country: "Argentina",
        firstAirDate: "June 24, 2019",
        lastAirDate: "July 24, 2020",
        status: "ended",
        language: "Spanish",
        plot: "Bia loves drawing and painting. She and her two best friends spend their time in the Fundom, a place where they and influencers enjoy showing their talents, especially dancing and singing. On the other hand, LAIX is a network where its CEO only wants fame and money.",
        numberOfSeasons: 2,
        numberOfEpisodes: 120,
        tags: ["Teen", "Drama", "Romance", "Music", "Telenovela"],
        network: ["Disney Channel Latin America"],
        related: [ "Soy Luna", "Bia: Un mundo al revés"]
    },
    {
        id: "wizards-of-waverly-place", 
        title: "Wizards of Waverly Place",
        posterUrl: "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p7896447_b_v13_aa.jpg",
        country: "United States",
        firstAirDate: "October 12, 2007",
        lastAirDate: "January 6, 2012",
        status: "ended",
        language: "English",
        plot: "The Russo family consists of three siblings who are wizards in training. They must compete to see who will become the family wizard, while also dealing with the challenges of growing up.",
        numberOfSeasons: 4,
        numberOfEpisodes: 106,
        tags: ["Comedy", "Fantasy", "Family"],
        network: ["Disney Channel"],
        related: ["The Wizards Return: Alex vs. Alex", "Wizards of Waverly Place: The Movie", "Wizards Beyond Waverly Place"]
    },
    {
        id: "austin-and-ally", 
        title: "Austin and Ally",
        posterUrl: "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p9901012_b_v8_aa.jpg",
        country: "United States",
        firstAirDate: "December 2, 2011",
        lastAirDate: "January 10, 2016",
        status: "ended",
        language: "English",
        plot: "Austin Moon is a talented singer and musician who becomes famous after Ally Dawson, a shy songwriter, writes a song for him. The two form a partnership and navigate the ups and downs of the music industry while also dealing with their personal lives.",
        numberOfSeasons: 4,
        numberOfEpisodes: 87,
        tags: ["Comedy", "Music", "Teen"],
    },
    {
        id: "penny-on-mars", 
        title: "Penny on M.A.R.S",
        posterUrl: "https://i.pinimg.com/736x/b1/68/73/b1687346a1dd837a051962ad25494f00.jpg",
        country: "Italy",
        firstAirDate: "May 7, 2018",
        lastAirDate: "July 3, 2020",
        status: "ended",
        language: "English",
        plot: "Following the adventures of Penny, a girl who has a big talent and a big passion: singing. Her mother is a famous singer so it probably runs in the family well anyway penny is always called by a different surname as no one knows her mother has a child so technically she's a secret baby. She decides to enroll in the most famous performing arts school, M.A.R.S. Her passion will encourage her to fight for her dreams alongside her best friend Camilla. And soon, the arrival of a boy will complicate things. You better watch this great show to get the rest of the details.",
        numberOfSeasons: 3,
        numberOfEpisodes: 39,
        tags: ["Drama", "Music", "Romance", "Teen"],
        network: ["Rai Gulp", "Disney Channel Italy"],
        related: ["Alex & Co"],
    },
    {
        id: "the-suite-life-on-deck", 
        title: "The Suite Life on Deck",
        posterUrl: "https://m.media-amazon.com/images/M/MV5BZTQ4NzRkNjItNTcyZS00YzgzLThjZjktNWI2YTM4NzE0MDdmXkEyXkFqcGc@._V1_.jpg",
        country: "United States",
        firstAirDate: "September 26, 2008",
        lastAirDate: "May 6, 2011",
        status: "ended",
        language: "English",
        plot: "The Suite Life on Deck is a spin-off of The Suite Life of Zack & Cody. The show follows the adventures of twin brothers Zack and Cody Martin as they attend high school on a cruise ship called the SS Tipton. Along with their friends, they navigate the challenges of teenage life while traveling the world.",
        numberOfSeasons: 3,
        numberOfEpisodes: 71,
        tags: ["Comedy", "Family", "Teen"],
        network: ["Disney Channel"],
        related: ["The Suite Life of Zack & Cody", "The Suite Life Movie"],
    },
    {
        id: "liv-and-maddie", 
        title: "Liv and Maddie",
        posterUrl: "https://m.media-amazon.com/images/M/MV5BYjRhMTYzZDMtYWJmZC00MWY3LTk5NzMtNjVjNDljYWNjM2E5XkEyXkFqcGc@._V1_.jpg",
        country: "United States",
        firstAirDate: "July 19, 2013",
        lastAirDate: "March 24, 2017",
        status: "ended",
        language: "English",
        plot: "Liv and Maddie are identical twin sisters with very different personalities. Liv is a famous actress, while Maddie is a basketball player. The show follows their lives as they navigate high school, family, and friendship.",
        numberOfSeasons: 4,
        numberOfEpisodes: 80,
        tags: ["Comedy", "Family", "Teen", "Music"],
        network: ["Disney Channel"],
    },
    {
        id: "violetta", 
        title: "Violetta",
        posterUrl: "https://filmgruvan.se/wp-content/uploads/2025/10/image-17.png",
        country: "Argentina",
        firstAirDate: "May 14, 2012",
        lastAirDate: "February 6, 2015",
        status: "ended",
        language: "Spanish",
        plot: "Violetta is a talented teenager who discovers her passion for music and singing. She attends a prestigious music school, Studio 21, where she meets new friends and faces challenges while pursuing her dreams.",
        numberOfSeasons: 3,
        numberOfEpisodes: 240,
        tags: ["Drama", "Music", "Romance", "Teen", "Telenovela"],
        network: ["Disney Channel Latin America"],
        related: ["Soy Luna", "Bia", "TINI: The Movie"],
    },
    {
        id: "hannah-montana", 
        title: "Hannah Montana",
        posterUrl: "https://image.tmdb.org/t/p/original/sRqLl0SHA4diTL8zvUTgBw6DQeM.jpg",
        country: "United States",
        firstAirDate: "March 24, 2006",
        lastAirDate: "January 16, 2011",
        status: "ended",
        language: "English",
        plot: "Miley Stewart is a normal teenager who lives a double life as the famous pop singer Hannah Montana. She navigates the challenges of fame, friendship, and family while trying to keep her secret identity hidden.",
        numberOfSeasons: 4,
        numberOfEpisodes: 98,
        tags: ["Comedy", "Music", "Family", "Teen"],
        network: ["Disney Channel"],
        related: ["Hannah Montana: The Movie", "Hannah Montana Forever", "Hannah Montana 20th Anniversary Special"],
    },
    {
        id: "good-luck-charlie", 
        title: "Good Luck Charlie",
        posterUrl: "https://mediaproxy.tvtropes.org/width/1200/https://static.tvtropes.org/pmwiki/pub/images/good_luck_charlie.png",
        country: "United States",
        firstAirDate: "April 4, 2010",
        lastAirDate: "February 16, 2014",
        status: "ended",
        language: "English",
        plot: "The Duncan family navigates the ups and downs of family life while raising their youngest daughter, Charlie. The show follows the family's adventures and challenges as they try to balance work, school, and personal lives.",
        numberOfSeasons: 4,
        numberOfEpisodes: 97,
        tags: ["Comedy", "Family", "Teen"],
        network: ["Disney Channel"],
        related: ["Good Luck Charlie: It's Christmas!", "Good Luck Charlie: The Road Trip", "Best of Luck Nikki"],
    },
    {
        id: "kc-undercover", 
        title: "K.C Undercover",
        posterUrl: "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p10771045_b_v11_ah.jpg",
        country: "United States",
        firstAirDate: "January 18, 2015",
        lastAirDate: "February 2, 2018",
        status: "ended",
        language: "English",
        plot: "K.C. Cooper is a high school student who becomes a spy for a secret government organization. She must balance her double life as a student and a spy while keeping her family safe from danger.",
        numberOfSeasons: 3,
        numberOfEpisodes: 75,
        tags: ["Comedy", "Action", "Family", "Teen"],
        network: ["Disney Channel"],
    },
    {
        id: "shake-it-up", 
        title: "Shake It Up",
        posterUrl: "https://i.pinimg.com/736x/f9/83/bc/f983bcb07a3c0fb5f32ffc5b8992b541.jpg",
        country: "United States",
        firstAirDate: "November 7, 2010",
        lastAirDate: "November 10, 2013",
        status: "ended",
        language: "English",
        plot: "Shake It Up follows the lives of two best friends, CeCe Jones and Rocky Blue, who land their dream jobs as backup dancers on a local dance show called 'Shake It Up Chicago.' The series showcases their adventures in the world of dance, friendship, and growing up.",
        numberOfSeasons: 3,
        numberOfEpisodes: 75,
        tags: ["Comedy", "Music", "Dance", "Teen"],
        network: ["Disney Channel"],
        related: ["Shake It Up: Made in Japan"],
    },
    {
        id: "sonny-with-a-chance", 
        title: "Sonny With a Chance",
        posterUrl: "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p7895977_b_v8_ab.jpg",
        country: "United States",
        firstAirDate: "February 8, 2009",
        lastAirDate: "January 2, 2011",
        status: "ended",
        language: "English",
        plot: "Talented Midwestern girl Sonny wins a nationwide talent search and is moving to Los Angeles to star in a popular TV series. Her home life and work life are documented along with her adjustment to life in the spotlight.",
        numberOfSeasons: 2,
        numberOfEpisodes: 47,
        tags: ["Comedy", "Family", "Teen"],
        network: ["Disney Channel"],
        related: ["So Random!"],
    },
    {
        id: "high-school-musical-the-musical-the-series", 
        title: "High School Musical the Musical the Series",
        posterUrl: "https://ew.com/thmb/FCKP8CAwSGBCLeMIXNHx4T5k9qA=/2000x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/high-school-musical-2-2000-6ae1ae2708f543e9ab27a95ba114caee.jpg",
        country: "United States",
        firstAirDate: "November 8, 2019",
        lastAirDate: "August 9, 2023",
        status: "ended",
        language: "English",
        plot: "A group of students at East High School stage a production of High School Musical, while navigating their own personal dramas and relationships.",
        numberOfSeasons: 4,
        numberOfEpisodes: 38,
        tags: ["Comedy", "Drama", "Music", "Romance", "Teen"],
        network: ["Disney+"],  
        related: ["High School Musical", "High School Musical 2", "High School Musical 3: Senior Year"],
    },
    {
        id: "pair-of-kings", 
        title: "Pair of Kings",
        posterUrl: "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p8248871_b_v8_ak.jpg",
        country: "United States",
        firstAirDate: "September 10, 2010",
        lastAirDate: "March 17, 2013",
        status: "ended",
        language: "English",
        plot: "Twin brothers, Brady and Boomer, discover they are the heirs to the throne of the island of Kinkow. They must learn to rule the island while dealing with various challenges and adventures.",
        numberOfSeasons: 3,
        numberOfEpisodes: 67,
        tags: ["Comedy", "Adventure", "Fantasy", "Teen"],
        network: ["Disney XD"],
    },
    {
        id: "kickin-it", 
        title: "Kickin' It",
        posterUrl: "https://m.media-amazon.com/images/M/MV5BMTYzMzg4MzI0Ml5BMl5BanBnXkFtZTcwMDM0MTEzNw@@._V1_.jpg",
        country: "United States",
        firstAirDate: "June 13, 2011",
        lastAirDate: "March 25, 2015",
        status: "ended",
        language: "English",
        plot: "Jack, Jerry, Milton, and Kim are four misfit teens who train in martial arts at the Bobby Wasabi Martial Arts Academy. They must work together to overcome challenges and protect their dojo from various threats.",
        numberOfSeasons: 4,
        numberOfEpisodes: 86,
        tags: ["Comedy", "Action", "Family", "Teen"],
        network: ["Disney XD"],  
    },
    {
        id: "jonas", 
        title: "J. O. N. A. S",
        posterUrl: "https://lumiere-a.akamaihd.net/v1/images/p_jonas_21237_5d76cc88.jpeg?region=0%2C0%2C540%2C810",
        country: "United States",
        firstAirDate: "May 2, 2009",
        lastAirDate: "October 30, 2010",
        status: "ended",
        language: "English",
        plot: "The Jonas Brothers star as themselves in this comedy series, which follows their lives as they navigate fame, friendship, and family while pursuing their music careers.",
        numberOfSeasons: 2,
        numberOfEpisodes: 34,
        tags: ["Comedy", "Music", "Family", "Teen"],
        network: ["Disney Channel"],
    },
    {
        id: "the-lodge", 
        title: "The Lodge",
        posterUrl: "https://media.themoviedb.org/t/p/w300_and_h450_face/9ujocbPizfuhhkWDvtH2ye3pezo.jpg",
        country: "United Kingdom",
        firstAirDate: "September 23, 2016",
        lastAirDate: "December 16, 2017",
        status: "ended",
        language: "English",
        plot: "The Lodge is a British teen drama series that follows the life of a teenage girl named Skye who moves to a remote lodge in the countryside to live with her father. She navigates the challenges of her new life, including friendships, romance, and family dynamics.",
        numberOfSeasons: 2,
        numberOfEpisodes: 25,
        tags: ["Drama", "Romance", "Music", "Teen"],
        network: ["Disney Channel UK"],  
    },
    {
        id: "the-suite-life-of-zack-and-cody", 
        title: "The Suite Life of Zack and Cody",
        posterUrl: "https://preview.redd.it/the-suite-life-of-zack-and-cody-premiered-on-this-day-in-v0-104wdf22yipe1.jpg?width=640&crop=smart&auto=webp&s=8bf59f9f433491832476d7a71730a263033858d4",
        country: "United States",
        firstAirDate: "March 18, 2005",
        lastAirDate: "September 1, 2008",
        status: "ended",
        language: "English",
        plot: "The Suite Life of Zack and Cody is a comedy series that follows the lives of twin brothers Zack and Cody Martin, who live in the Tipton Hotel with their mother, who works as a lounge singer. The show explores their adventures and misadventures as they navigate life in the hotel, school, and friendships.",
        numberOfSeasons: 3,
        numberOfEpisodes: 87,
        tags: ["Comedy", "Family", "Teen"],
        network: ["Disney Channel"],
        related: ["The Suite On Deck", "The Suite Life Movie"],
    },
    {
        id: "ant-farm", 
        title: "A.N.T Farm",
        posterUrl: "https://mediaproxy.tvtropes.org/width/1200/https://static.tvtropes.org/pmwiki/pub/images/17360.jpg",
        country: "United States",
        firstAirDate: "May 6, 2011",
        lastAirDate: "March 21, 2014",
        status: "ended",
        language: "English",
        plot: "A.N.T. Farm is a comedy series that follows the lives of three gifted middle school students, Chyna, Olive, and Fletcher, who are part of the Advanced Natural Talents (A.N.T.) program at Webster High School. The show explores their adventures, friendships, and challenges as they navigate life in a school for talented students.",
        numberOfSeasons: 3,
        numberOfEpisodes: 62,   
        tags: ["Comedy", "Family", "Teen", "Music"],
        network: ["Disney Channel"],
    },
    {
        id: "i-didnt-do-it", 
        title: "I Didn't Do It",
        posterUrl: "https://i.pinimg.com/736x/12/e3/eb/12e3eb827ba5e5ca02a31aa62fded2e0.jpg",
        country: "United States",
        firstAirDate: "January 17, 2014",
        lastAirDate: "October 16, 2015",
        status: "ended",
        language: "English",
        plot: "I Didn't Do It is a comedy series that follows the lives of five high school friends, Lindy, Logan, Jasmine, Garrett, and Delia, as they navigate the challenges of teenage life. The show explores their adventures, friendships, and misadventures as they deal with school, relationships, and family.",
        numberOfSeasons: 2,
        numberOfEpisodes: 39,
        tags: ["Comedy", "Family", "Teen"],
        network: ["Disney Channel"],
    },
    {
        id: "girl-meets-world ", 
        title: "Girl Meets World",
        posterUrl: "https://preview.redd.it/girl-meets-world-could-have-been-great-but-it-was-executed-v0-hoz1fawija5c1.jpg?width=1080&crop=smart&auto=webp&s=18a05df2752c33106676ecc46d0b8bc58badf255",
        country: "United States",
        firstAirDate: "June 27, 2014",
        lastAirDate: "January 20, 2017",
        status: "ended",
        language: "English",
        plot: "Girl Meets World follows Riley Matthews, the preteen daughter of Cory and Topanga Matthews, as she navigates middle school, family life, and growing up in New York City alongside her rebellious best friend Maya Hart. Cory serves as her history teacher, blending school lessons with life advice.",
        numberOfSeasons: 3,
        numberOfEpisodes: 72,
        tags: ["Comedy", "Family", "Teen"],
        network: ["Disney Channel"],
        related: ["Boy Meets World"],
    },
    {
        id: "alex-and-co", 
        title: "Alex and Co.",
        posterUrl: "https://pics.filmaffinity.com/alex_co_tv_series-488434836-large.jpg",
        country: "Italy",
        firstAirDate: "May 11, 2015",
        lastAirDate: "October 30, 2017",
        status: "ended",
        language: "Italian",
        plot: "Alex and Co. is an Italian teen drama series that follows the lives of a group of high school students who form a band. The show explores their friendships, romances, and challenges as they navigate the ups and downs of teenage life while pursuing their passion for music.",
        numberOfSeasons: 3,
        numberOfEpisodes: 55,
        tags: ["Drama", "Music", "Romance", "Teen"],
        network: ["Disney Channel Italy"],
        related: ["Penny on M.A.R.S", "Alex & Co: The Movie"],
    },

]